// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCashTransaction(ctx context.Context, arg CreateCashTransactionParams) (CashTransaction, error)
	CreateShift(ctx context.Context, arg CreateShiftParams) (Shift, error)
	EndShift(ctx context.Context, arg EndShiftParams) (Shift, error)
	GetCashTotalByShiftIDAndType(ctx context.Context, arg GetCashTotalByShiftIDAndTypeParams) (int64, error)
	GetCashTransactionsByShiftID(ctx context.Context, shiftID uuid.UUID) ([]CashTransaction, error)
	GetOpenShiftByUserID(ctx context.Context, userID uuid.UUID) (Shift, error)
	GetShiftByID(ctx context.Context, id uuid.UUID) (Shift, error)
	GetUserPasswordHash(ctx context.Context, id uuid.UUID) (string, error)
}

var _ Querier = (*Queries)(nil)
