// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shifts.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createCashTransaction = `-- name: CreateCashTransaction :one
INSERT INTO cash_transactions (
    shift_id, user_id, amount, type, category, description
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, shift_id, user_id, amount, type, category, description, created_at
`

type CreateCashTransactionParams struct {
	ShiftID     uuid.UUID           `json:"shift_id"`
	UserID      uuid.UUID           `json:"user_id"`
	Amount      int64               `json:"amount"`
	Type        CashTransactionType `json:"type"`
	Category    string              `json:"category"`
	Description *string             `json:"description"`
}

func (q *Queries) CreateCashTransaction(ctx context.Context, arg CreateCashTransactionParams) (CashTransaction, error) {
	row := q.db.QueryRow(ctx, createCashTransaction,
		arg.ShiftID,
		arg.UserID,
		arg.Amount,
		arg.Type,
		arg.Category,
		arg.Description,
	)
	var i CashTransaction
	err := row.Scan(
		&i.ID,
		&i.ShiftID,
		&i.UserID,
		&i.Amount,
		&i.Type,
		&i.Category,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createShift = `-- name: CreateShift :one
INSERT INTO shifts (
    user_id, start_cash, status
) VALUES (
    $1, $2, 'open'
) RETURNING id, user_id, start_time, end_time, start_cash, expected_cash_end, actual_cash_end, status, created_at, updated_at
`

type CreateShiftParams struct {
	UserID    uuid.UUID `json:"user_id"`
	StartCash int64     `json:"start_cash"`
}

func (q *Queries) CreateShift(ctx context.Context, arg CreateShiftParams) (Shift, error) {
	row := q.db.QueryRow(ctx, createShift, arg.UserID, arg.StartCash)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartTime,
		&i.EndTime,
		&i.StartCash,
		&i.ExpectedCashEnd,
		&i.ActualCashEnd,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const endShift = `-- name: EndShift :one
UPDATE shifts
SET 
    end_time = NOW(),
    expected_cash_end = $2,
    actual_cash_end = $3,
    status = 'closed',
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, start_time, end_time, start_cash, expected_cash_end, actual_cash_end, status, created_at, updated_at
`

type EndShiftParams struct {
	ID              uuid.UUID `json:"id"`
	ExpectedCashEnd *int64    `json:"expected_cash_end"`
	ActualCashEnd   *int64    `json:"actual_cash_end"`
}

func (q *Queries) EndShift(ctx context.Context, arg EndShiftParams) (Shift, error) {
	row := q.db.QueryRow(ctx, endShift, arg.ID, arg.ExpectedCashEnd, arg.ActualCashEnd)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartTime,
		&i.EndTime,
		&i.StartCash,
		&i.ExpectedCashEnd,
		&i.ActualCashEnd,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCashTotalByShiftIDAndType = `-- name: GetCashTotalByShiftIDAndType :one
SELECT COALESCE(SUM(amount), 0)::bigint FROM cash_transactions
WHERE shift_id = $1 AND type = $2
`

type GetCashTotalByShiftIDAndTypeParams struct {
	ShiftID uuid.UUID           `json:"shift_id"`
	Type    CashTransactionType `json:"type"`
}

func (q *Queries) GetCashTotalByShiftIDAndType(ctx context.Context, arg GetCashTotalByShiftIDAndTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, getCashTotalByShiftIDAndType, arg.ShiftID, arg.Type)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getCashTransactionsByShiftID = `-- name: GetCashTransactionsByShiftID :many
SELECT id, shift_id, user_id, amount, type, category, description, created_at FROM cash_transactions
WHERE shift_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetCashTransactionsByShiftID(ctx context.Context, shiftID uuid.UUID) ([]CashTransaction, error) {
	rows, err := q.db.Query(ctx, getCashTransactionsByShiftID, shiftID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CashTransaction{}
	for rows.Next() {
		var i CashTransaction
		if err := rows.Scan(
			&i.ID,
			&i.ShiftID,
			&i.UserID,
			&i.Amount,
			&i.Type,
			&i.Category,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOpenShiftByUserID = `-- name: GetOpenShiftByUserID :one
SELECT id, user_id, start_time, end_time, start_cash, expected_cash_end, actual_cash_end, status, created_at, updated_at FROM shifts
WHERE user_id = $1 AND status = 'open'
LIMIT 1
`

func (q *Queries) GetOpenShiftByUserID(ctx context.Context, userID uuid.UUID) (Shift, error) {
	row := q.db.QueryRow(ctx, getOpenShiftByUserID, userID)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartTime,
		&i.EndTime,
		&i.StartCash,
		&i.ExpectedCashEnd,
		&i.ActualCashEnd,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShiftByID = `-- name: GetShiftByID :one
SELECT id, user_id, start_time, end_time, start_cash, expected_cash_end, actual_cash_end, status, created_at, updated_at FROM shifts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetShiftByID(ctx context.Context, id uuid.UUID) (Shift, error) {
	row := q.db.QueryRow(ctx, getShiftByID, id)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartTime,
		&i.EndTime,
		&i.StartCash,
		&i.ExpectedCashEnd,
		&i.ActualCashEnd,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPasswordHash = `-- name: GetUserPasswordHash :one
SELECT password_hash FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserPasswordHash(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserPasswordHash, id)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}
