
FROM golang:1.25-alpine
WORKDIR /app


RUN apk --no-cache add build-base


RUN go install github.com/air-verse/air@latest


ENV DOCKERIZE_VERSION v0.7.0
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz


COPY go.mod go.sum ./
RUN go mod download


CMD ["air"]