// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountPromotions(ctx context.Context) (int64, error)
	CountTrashPromotions(ctx context.Context) (int64, error)
	CreatePromotion(ctx context.Context, arg CreatePromotionParams) (Promotion, error)
	CreatePromotionRule(ctx context.Context, arg CreatePromotionRuleParams) (PromotionRule, error)
	CreatePromotionTarget(ctx context.Context, arg CreatePromotionTargetParams) (PromotionTarget, error)
	DeletePromotion(ctx context.Context, id uuid.UUID) error
	DeletePromotionRulesByPromotionID(ctx context.Context, promotionID uuid.UUID) error
	DeletePromotionTargetsByPromotionID(ctx context.Context, promotionID uuid.UUID) error
	GetActivePromotionByID(ctx context.Context, id uuid.UUID) (Promotion, error)
	// Mengambil detail promosi berdasarkan ID.
	GetPromotionByID(ctx context.Context, id uuid.UUID) (Promotion, error)
	// Mengambil semua aturan untuk sebuah promosi.
	GetPromotionRules(ctx context.Context, promotionID uuid.UUID) ([]PromotionRule, error)
	// Mengambil semua target untuk sebuah promosi.
	GetPromotionTargets(ctx context.Context, promotionID uuid.UUID) ([]PromotionTarget, error)
	ListPromotions(ctx context.Context, arg ListPromotionsParams) ([]Promotion, error)
	ListTrashPromotions(ctx context.Context, arg ListTrashPromotionsParams) ([]Promotion, error)
	RestorePromotion(ctx context.Context, id uuid.UUID) error
	UpdatePromotion(ctx context.Context, arg UpdatePromotionParams) (Promotion, error)
}

var _ Querier = (*Queries)(nil)
