// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
)

type Querier interface {
	// Membuat alasan pembatalan baru.
	CreateCancellationReason(ctx context.Context, arg CreateCancellationReasonParams) (CancellationReason, error)
	// Mengambil satu alasan pembatalan berdasarkan teks alasannya untuk pengecekan duplikat.
	GetCancellationReasonByReason(ctx context.Context, reason string) (CancellationReason, error)
	// Mengambil daftar semua alasan pembatalan yang aktif.
	ListCancellationReasons(ctx context.Context) ([]CancellationReason, error)
}

var _ Querier = (*Queries)(nil)
