// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity_log.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createActivityLog = `-- name: CreateActivityLog :one
INSERT INTO activity_logs (
    user_id,
    action_type,
    entity_type,
    entity_id,
    details
) VALUES (
             $1, $2, $3, $4, $5
         ) RETURNING id
`

type CreateActivityLogParams struct {
	UserID     pgtype.UUID   `json:"user_id"`
	ActionType LogActionType `json:"action_type"`
	EntityType LogEntityType `json:"entity_type"`
	EntityID   string        `json:"entity_id"`
	Details    []byte        `json:"details"`
}

func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createActivityLog,
		arg.UserID,
		arg.ActionType,
		arg.EntityType,
		arg.EntityID,
		arg.Details,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
