// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Menambahkan stok kembali ke sebuah produk (digunakan saat pesanan dibatalkan).
	AddProductStock(ctx context.Context, arg AddProductStockParams) (AddProductStockRow, error)
	BatchCreateOrderItemOptions(ctx context.Context, arg []BatchCreateOrderItemOptionsParams) (int64, error)
	// Memasukkan banyak item sekaligus menggunakan array (Bulk Insert).
	BatchCreateOrderItems(ctx context.Context, arg BatchCreateOrderItemsParams) ([]OrderItem, error)
	// Mengurangi stok banyak produk sekaligus berdasarkan pasangan ID dan Qty.
	BatchDecreaseProductStock(ctx context.Context, arg BatchDecreaseProductStockParams) error
	// Mengubah status pesanan menjadi 'cancelled' dan mencatat alasannya.
	// Hanya bisa membatalkan pesanan yang statusnya 'open'.
	CancelOrder(ctx context.Context, arg CancelOrderParams) (Order, error)
	// Hanya memeriksa keberadaan pengguna yang aktif.
	CheckUserExistence(ctx context.Context, arg CheckUserExistenceParams) (CheckUserExistenceRow, error)
	// Hanya menghitung pengguna yang aktif dan belum dihapus.
	CountActiveUsers(ctx context.Context) (int64, error)
	CountActivityLogs(ctx context.Context, arg CountActivityLogsParams) (int64, error)
	// Menghitung total jumlah kategori, berguna untuk pagination.
	CountCategories(ctx context.Context) (int64, error)
	CountDeletedProducts(ctx context.Context, arg CountDeletedProductsParams) (int64, error)
	// Hanya menghitung pengguna yang tidak aktif dan belum dihapus.
	CountInactiveUsers(ctx context.Context) (int64, error)
	// Menghitung total pesanan dengan filter.
	CountOrders(ctx context.Context, arg CountOrdersParams) (int64, error)
	// Counts total products for pagination, respecting filters.
	CountProducts(ctx context.Context, arg CountProductsParams) (int64, error)
	CountProductsInCategory(ctx context.Context, categoryID *int32) (int64, error)
	CountPromotions(ctx context.Context) (int64, error)
	CountTrashPromotions(ctx context.Context) (int64, error)
	// Menghitung pengguna dengan filter status.
	CountUsers(ctx context.Context, arg CountUsersParams) (int64, error)
	CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (uuid.UUID, error)
	// Membuat alasan pembatalan baru.
	CreateCancellationReason(ctx context.Context, arg CreateCancellationReasonParams) (CancellationReason, error)
	// Membuat kategori baru dan mengembalikan data lengkapnya.
	CreateCategory(ctx context.Context, name string) (Category, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	// Menambahkan satu item produk ke dalam pesanan.
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	// Menambahkan satu varian/opsi ke dalam sebuah order item.
	CreateOrderItemOption(ctx context.Context, arg CreateOrderItemOptionParams) (OrderItemOption, error)
	// Membuat metode pembayaran baru.
	CreatePaymentMethod(ctx context.Context, name string) (PaymentMethod, error)
	// Queries for Products
	// Creates a new product and returns its full details.
	// Product options should be created separately in a transaction.
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	// Queries for Product Options (Variants)
	// Creates a new option for a specific product.
	CreateProductOption(ctx context.Context, arg CreateProductOptionParams) (ProductOption, error)
	CreatePromotion(ctx context.Context, arg CreatePromotionParams) (Promotion, error)
	CreatePromotionRule(ctx context.Context, arg CreatePromotionRuleParams) (PromotionRule, error)
	CreatePromotionTarget(ctx context.Context, arg CreatePromotionTargetParams) (PromotionTarget, error)
	// Tidak ada perubahan, deleted_at akan NULL secara default.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Mengurangi stok produk.
	DecreaseProductStock(ctx context.Context, arg DecreaseProductStockParams) (Product, error)
	// Menghapus satu kategori berdasarkan ID.
	DeleteCategory(ctx context.Context, id int32) error
	// Menghapus satu item dari pesanan.
	DeleteOrderItem(ctx context.Context, arg DeleteOrderItemParams) error
	DeleteOrderItemOptionsByOrderItemID(ctx context.Context, orderItemID uuid.UUID) error
	DeleteOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) error
	// Deletes a product. Its options will be deleted automatically due to 'ON DELETE CASCADE'.
	DeleteProduct(ctx context.Context, id uuid.UUID) error
	DeletePromotion(ctx context.Context, id uuid.UUID) error
	DeletePromotionRulesByPromotionID(ctx context.Context, promotionID uuid.UUID) error
	DeletePromotionTargetsByPromotionID(ctx context.Context, promotionID uuid.UUID) error
	// Mengubah DELETE menjadi UPDATE untuk soft delete.
	DeleteUser(ctx context.Context, id uuid.UUID) error
	// Memeriksa apakah kategori dengan ID tertentu ada.
	ExistsCategory(ctx context.Context, id int32) (bool, error)
	GetActivePromotionByID(ctx context.Context, id uuid.UUID) (Promotion, error)
	GetActivityLogs(ctx context.Context, arg GetActivityLogsParams) ([]GetActivityLogsRow, error)
	// Mengambil satu alasan pembatalan berdasarkan teks alasannya untuk pengecekan duplikat.
	GetCancellationReasonByReason(ctx context.Context, reason string) (CancellationReason, error)
	GetCancellationReasons(ctx context.Context, arg GetCancellationReasonsParams) ([]GetCancellationReasonsRow, error)
	GetCashierPerformance(ctx context.Context, arg GetCashierPerformanceParams) ([]GetCashierPerformanceRow, error)
	// Mengambil satu kategori berdasarkan ID.
	GetCategory(ctx context.Context, id int32) (Category, error)
	GetCategorySales(ctx context.Context, arg GetCategorySalesParams) ([]GetCategorySalesRow, error)
	GetDashboardSummary(ctx context.Context) (GetDashboardSummaryRow, error)
	GetDeletedProduct(ctx context.Context, id uuid.UUID) (GetDeletedProductRow, error)
	// Mengambil semua varian untuk beberapa produk.
	GetOptionsForProducts(ctx context.Context, dollar_1 []uuid.UUID) ([]ProductOption, error)
	// Mengambil pesanan berdasarkan referensi dari payment gateway.
	GetOrderByGatewayRef(ctx context.Context, paymentGatewayReference *string) (Order, error)
	// Mengambil satu pesanan dan mengunci barisnya untuk pembaruan (mencegah race condition).
	// Penting untuk digunakan di dalam transaksi sebelum mengupdate total.
	GetOrderForUpdate(ctx context.Context, id uuid.UUID) (Order, error)
	// Mengambil satu item pesanan untuk validasi sebelum update/delete.
	GetOrderItem(ctx context.Context, arg GetOrderItemParams) (OrderItem, error)
	// Mengambil semua item dari sebuah pesanan untuk menghitung ulang total.
	GetOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error)
	// Mengambil detail lengkap pesanan, termasuk item dan opsinya dalam format JSON.
	GetOrderWithDetails(ctx context.Context, id uuid.UUID) (GetOrderWithDetailsRow, error)
	// Mengambil satu metode pembayaran berdasarkan nama untuk pengecekan duplikat.
	GetPaymentMethodByName(ctx context.Context, name string) (PaymentMethod, error)
	GetPaymentMethodSales(ctx context.Context, arg GetPaymentMethodSalesParams) ([]GetPaymentMethodSalesRow, error)
	// Retrieves a product by its ID, including its options.
	GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error)
	// Mengambil satu varian produk berdasarkan ID dan ID produk induknya.
	GetProductOption(ctx context.Context, arg GetProductOptionParams) (ProductOption, error)
	// Retrieves a product option by its ID, including its product details.
	GetProductOptionByID(ctx context.Context, id uuid.UUID) (GetProductOptionByIDRow, error)
	GetProductOptionsByIDs(ctx context.Context, ids []uuid.UUID) ([]ProductOption, error)
	GetProductSalesPerformance(ctx context.Context, arg GetProductSalesPerformanceParams) ([]GetProductSalesPerformanceRow, error)
	// Retrieves a single product and aggregates its options into a JSON array.
	// This is an efficient way to fetch a product and its variants in one query.
	// Now filters out soft-deleted options.
	GetProductWithOptions(ctx context.Context, id uuid.UUID) (GetProductWithOptionsRow, error)
	// Mengambil beberapa produk berdasarkan array ID. Ini untuk menghindari N+1 query.
	GetProductsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Product, error)
	// Mengambil produk sekaligus mengunci barisnya (Row-Level Locking).
	// Transaksi lain yang mencoba update produk ini harus menunggu sampai transaksi ini selesai.
	GetProductsForUpdate(ctx context.Context, dollar_1 []uuid.UUID) ([]Product, error)
	// Mengambil detail promosi berdasarkan ID.
	GetPromotionByID(ctx context.Context, id uuid.UUID) (Promotion, error)
	// Mengambil semua aturan untuk sebuah promosi.
	GetPromotionRules(ctx context.Context, promotionID uuid.UUID) ([]PromotionRule, error)
	// Mengambil semua target untuk sebuah promosi.
	GetPromotionTargets(ctx context.Context, promotionID uuid.UUID) ([]PromotionTarget, error)
	GetSalesSummary(ctx context.Context, arg GetSalesSummaryParams) ([]GetSalesSummaryRow, error)
	GetSettingByKey(ctx context.Context, key string) (Setting, error)
	GetSettings(ctx context.Context) ([]Setting, error)
	// Mengambil satu pengguna berdasarkan email, hanya jika pengguna tersebut aktif.
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Mengambil satu pengguna berdasarkan ID, hanya jika pengguna tersebut aktif.
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// Mengambil satu pengguna berdasarkan username, hanya jika pengguna tersebut aktif.
	GetUserByUsername(ctx context.Context, username string) (User, error)
	// Mengambil daftar semua alasan pembatalan yang aktif.
	ListCancellationReasons(ctx context.Context) ([]CancellationReason, error)
	// Mengambil daftar semua kategori dengan pagination.
	ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error)
	// Mengambil daftar kategori beserta jumlah produk yang ada di setiap kategori.
	ListCategoriesWithProducts(ctx context.Context, arg ListCategoriesWithProductsParams) ([]ListCategoriesWithProductsRow, error)
	ListDeletedProducts(ctx context.Context, arg ListDeletedProductsParams) ([]ListDeletedProductsRow, error)
	// Retrieves all options for a single product.
	ListOptionsForProduct(ctx context.Context, productID uuid.UUID) ([]ProductOption, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]ListOrdersRow, error)
	// Mengambil daftar semua metode pembayaran yang aktif.
	ListPaymentMethods(ctx context.Context) ([]PaymentMethod, error)
	// Lists products with filtering and pagination.
	// Does not include variants for performance reasons on a list view.
	ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error)
	ListPromotions(ctx context.Context, arg ListPromotionsParams) ([]Promotion, error)
	ListTrashPromotions(ctx context.Context, arg ListTrashPromotionsParams) ([]Promotion, error)
	// Mengambil daftar pengguna dengan filter, pagination, dan status (aktif/dihapus/semua).
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	RestoreProduct(ctx context.Context, id uuid.UUID) error
	RestoreProductsBulk(ctx context.Context, dollar_1 []uuid.UUID) error
	RestorePromotion(ctx context.Context, id uuid.UUID) error
	SoftDeleteProduct(ctx context.Context, id uuid.UUID) error
	// Deletes a single product option.
	SoftDeleteProductOption(ctx context.Context, id uuid.UUID) error
	// Hanya bisa mengubah status pengguna yang belum dihapus.
	ToggleUserActiveStatus(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	// Memperbarui nama kategori dan mengembalikan data yang sudah diperbarui.
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateOrderAppliedPromotion(ctx context.Context, arg UpdateOrderAppliedPromotionParams) error
	// Update qty dan subtotal. Penting: Tambahkan validasi stok/constraint di level aplikasi
	// atau pastikan trigger handle pengurangan stok jika qty bertambah.
	UpdateOrderItemQuantity(ctx context.Context, arg UpdateOrderItemQuantityParams) (OrderItem, error)
	// Memperbarui pesanan untuk pembayaran manual (tunai, dll.) dan mengubah status menjadi 'paid'.
	// Hanya bisa memproses pesanan yang statusnya 'open'.
	UpdateOrderManualPayment(ctx context.Context, arg UpdateOrderManualPaymentParams) (Order, error)
	// Menyimpan referensi pembayaran dari payment gateway dan metode pembayaran.
	UpdateOrderPaymentInfo(ctx context.Context, arg UpdateOrderPaymentInfoParams) error
	// Menyimpan URL pembayaran (QR string atau deep link) dan token.
	UpdateOrderPaymentUrl(ctx context.Context, arg UpdateOrderPaymentUrlParams) error
	// Memperbarui status operasional sebuah pesanan.
	// Validasi transisi status dilakukan di level aplikasi/service.
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	// Memperbarui status pesanan berdasarkan referensi dari payment gateway (digunakan oleh webhook).
	UpdateOrderStatusByGatewayRef(ctx context.Context, arg UpdateOrderStatusByGatewayRefParams) (Order, error)
	// Memperbarui total harga, diskon, dan total bersih dari sebuah pesanan.
	UpdateOrderTotals(ctx context.Context, arg UpdateOrderTotalsParams) (Order, error)
	// Updates a product's details. Use COALESCE for optional fields.
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	// Updates a specific product option.
	UpdateProductOption(ctx context.Context, arg UpdateProductOptionParams) (ProductOption, error)
	UpdatePromotion(ctx context.Context, arg UpdatePromotionParams) (Promotion, error)
	// Memperbarui refresh token pengguna (Single Session Enforcement).
	UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) error
	UpdateSetting(ctx context.Context, arg UpdateSettingParams) (Setting, error)
	// Memperbarui pengguna aktif.
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	// Hanya bisa mengubah password pengguna aktif.
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	// Mengubah :exec menjadi :one dan menambahkan RETURNING untuk konfirmasi.
	// Hanya bisa mengubah peran pengguna aktif.
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) (Setting, error)
}

var _ Querier = (*Queries)(nil)
