// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveUsers = `-- name: CountActiveUsers :one
SELECT COUNT(*) FROM users WHERE is_active = true
`

func (q *Queries) CountActiveUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countInactiveUsers = `-- name: CountInactiveUsers :one
SELECT COUNT(*) FROM users WHERE is_active = false
`

func (q *Queries) CountInactiveUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countInactiveUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id,username, email, password_hash, avatar, role, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, username, email, password_hash, created_at, updated_at, avatar, role, is_active
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Avatar       *string   `json:"avatar"`
	Role         UserRole  `json:"role"`
	IsActive     bool      `json:"is_active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Avatar,
		arg.Role,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Avatar,
		&i.Role,
		&i.IsActive,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, created_at, updated_at, avatar, role, is_active
FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Avatar,
		&i.Role,
		&i.IsActive,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, created_at, updated_at, avatar, role, is_active
FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Avatar,
		&i.Role,
		&i.IsActive,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, created_at, updated_at, avatar, role, is_active
FROM users WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Avatar,
		&i.Role,
		&i.IsActive,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, avatar, role, is_active, created_at, updated_at
FROM users
WHERE
    (
        ($3::text IS NULL OR username ILIKE '%' || $3 || '%')
            OR
        ($3::text IS NULL OR email ILIKE '%' || $3 || '%')
        )
  AND ($4::user_role IS NULL OR role = $4)
  AND ($5::bool IS NULL OR is_active = $5)
ORDER BY
  CASE WHEN $6::user_order_column = 'username' AND $7::sort_order = 'asc'  THEN username END ASC,
  CASE WHEN $6::user_order_column = 'username' AND $7::sort_order = 'desc' THEN username END DESC,
  CASE WHEN $6::user_order_column = 'email' AND $7::sort_order = 'asc' THEN email END ASC,
  CASE WHEN $6::user_order_column = 'email' AND $7::sort_order = 'desc' THEN email END DESC,
  CASE WHEN $6::user_order_column = 'created_at' AND $7::sort_order = 'asc' THEN created_at END ASC,
  CASE WHEN $6::user_order_column = 'created_at' AND $7::sort_order = 'desc' THEN created_at END DESC,
  created_at ASC

LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit      int32           `json:"limit"`
	Offset     int32           `json:"offset"`
	SearchText *string         `json:"search_text"`
	Role       NullUserRole    `json:"role"`
	IsActive   *bool           `json:"is_active"`
	OrderBy    UserOrderColumn `json:"order_by"`
	SortOrder  SortOrder       `json:"sort_order"`
}

type ListUsersRow struct {
	ID        uuid.UUID          `json:"id"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	Avatar    *string            `json:"avatar"`
	Role      UserRole           `json:"role"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Limit,
		arg.Offset,
		arg.SearchText,
		arg.Role,
		arg.IsActive,
		arg.OrderBy,
		arg.SortOrder,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Avatar,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleUserActiveStatus = `-- name: ToggleUserActiveStatus :exec
UPDATE users
SET is_active = NOT is_active
WHERE id = $1
`

func (q *Queries) ToggleUserActiveStatus(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, toggleUserActiveStatus, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    username = COALESCE($2, username),
    email = COALESCE($3, email),
    avatar = COALESCE($4, avatar),
    is_active = COALESCE($5, is_active)
WHERE id = $1
RETURNING id, username, email, password_hash, created_at, updated_at, avatar, role, is_active
`

type UpdateUserParams struct {
	ID       uuid.UUID `json:"id"`
	Username *string   `json:"username"`
	Email    *string   `json:"email"`
	Avatar   *string   `json:"avatar"`
	IsActive *bool     `json:"is_active"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Avatar,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Avatar,
		&i.Role,
		&i.IsActive,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users
SET role = $2
WHERE id = $1
RETURNING id, username, email, password_hash, created_at, updated_at, avatar, role, is_active
`

type UpdateUserRoleParams struct {
	ID   uuid.UUID `json:"id"`
	Role UserRole  `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.ID, arg.Role)
	return err
}
