// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountActivityLogs(ctx context.Context, arg CountActivityLogsParams) (int64, error)
	CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (uuid.UUID, error)
	GetActivityLogs(ctx context.Context, arg GetActivityLogsParams) ([]GetActivityLogsRow, error)
}

var _ Querier = (*Queries)(nil)
