// Code generated by MockGen. DO NOT EDIT.
// Source: internal/user/user_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/user/user_service.go -destination=mocks/mock_user_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	user "POS-kasir/internal/user"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockIUsrService is a mock of IUsrService interface.
type MockIUsrService struct {
	ctrl     *gomock.Controller
	recorder *MockIUsrServiceMockRecorder
	isgomock struct{}
}

// MockIUsrServiceMockRecorder is the mock recorder for MockIUsrService.
type MockIUsrServiceMockRecorder struct {
	mock *MockIUsrService
}

// NewMockIUsrService creates a new mock instance.
func NewMockIUsrService(ctrl *gomock.Controller) *MockIUsrService {
	mock := &MockIUsrService{ctrl: ctrl}
	mock.recorder = &MockIUsrServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUsrService) EXPECT() *MockIUsrServiceMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockIUsrService) CreateUser(ctx context.Context, req user.CreateUserRequest) (*user.ProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, req)
	ret0, _ := ret[0].(*user.ProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockIUsrServiceMockRecorder) CreateUser(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockIUsrService)(nil).CreateUser), ctx, req)
}

// DeleteUser mocks base method.
func (m *MockIUsrService) DeleteUser(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockIUsrServiceMockRecorder) DeleteUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockIUsrService)(nil).DeleteUser), ctx, userID)
}

// GetAllUsers mocks base method.
func (m *MockIUsrService) GetAllUsers(ctx context.Context, req user.UsersRequest) (*user.UsersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUsers", ctx, req)
	ret0, _ := ret[0].(*user.UsersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUsers indicates an expected call of GetAllUsers.
func (mr *MockIUsrServiceMockRecorder) GetAllUsers(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUsers", reflect.TypeOf((*MockIUsrService)(nil).GetAllUsers), ctx, req)
}

// GetUserByID mocks base method.
func (m *MockIUsrService) GetUserByID(ctx context.Context, userID uuid.UUID) (*user.ProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(*user.ProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockIUsrServiceMockRecorder) GetUserByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockIUsrService)(nil).GetUserByID), ctx, userID)
}

// ToggleUserStatus mocks base method.
func (m *MockIUsrService) ToggleUserStatus(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleUserStatus", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToggleUserStatus indicates an expected call of ToggleUserStatus.
func (mr *MockIUsrServiceMockRecorder) ToggleUserStatus(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleUserStatus", reflect.TypeOf((*MockIUsrService)(nil).ToggleUserStatus), ctx, userID)
}

// UpdateUser mocks base method.
func (m *MockIUsrService) UpdateUser(ctx context.Context, userID uuid.UUID, req user.UpdateUserRequest) (*user.ProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, userID, req)
	ret0, _ := ret[0].(*user.ProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockIUsrServiceMockRecorder) UpdateUser(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockIUsrService)(nil).UpdateUser), ctx, userID, req)
}
