// Code generated by MockGen. DO NOT EDIT.
// Source: POS-kasir/internal/shift (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=mocks/mock_shift_service.go POS-kasir/internal/shift Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	shift "POS-kasir/internal/shift"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AutoCloseShifts mocks base method.
func (m *MockService) AutoCloseShifts(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AutoCloseShifts", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// AutoCloseShifts indicates an expected call of AutoCloseShifts.
func (mr *MockServiceMockRecorder) AutoCloseShifts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AutoCloseShifts", reflect.TypeOf((*MockService)(nil).AutoCloseShifts), ctx)
}

// CreateCashTransaction mocks base method.
func (m *MockService) CreateCashTransaction(ctx context.Context, userID uuid.UUID, req shift.CashTransactionRequest) (*shift.CashTransactionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCashTransaction", ctx, userID, req)
	ret0, _ := ret[0].(*shift.CashTransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCashTransaction indicates an expected call of CreateCashTransaction.
func (mr *MockServiceMockRecorder) CreateCashTransaction(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCashTransaction", reflect.TypeOf((*MockService)(nil).CreateCashTransaction), ctx, userID, req)
}

// EndShift mocks base method.
func (m *MockService) EndShift(ctx context.Context, userID uuid.UUID, req shift.EndShiftRequest) (*shift.ShiftResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndShift", ctx, userID, req)
	ret0, _ := ret[0].(*shift.ShiftResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EndShift indicates an expected call of EndShift.
func (mr *MockServiceMockRecorder) EndShift(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndShift", reflect.TypeOf((*MockService)(nil).EndShift), ctx, userID, req)
}

// GetOpenShift mocks base method.
func (m *MockService) GetOpenShift(ctx context.Context, userID uuid.UUID) (*shift.ShiftResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpenShift", ctx, userID)
	ret0, _ := ret[0].(*shift.ShiftResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOpenShift indicates an expected call of GetOpenShift.
func (mr *MockServiceMockRecorder) GetOpenShift(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpenShift", reflect.TypeOf((*MockService)(nil).GetOpenShift), ctx, userID)
}

// StartShift mocks base method.
func (m *MockService) StartShift(ctx context.Context, userID uuid.UUID, req shift.StartShiftRequest) (*shift.ShiftResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartShift", ctx, userID, req)
	ret0, _ := ret[0].(*shift.ShiftResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartShift indicates an expected call of StartShift.
func (mr *MockServiceMockRecorder) StartShift(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartShift", reflect.TypeOf((*MockService)(nil).StartShift), ctx, userID, req)
}
