// Code generated by MockGen. DO NOT EDIT.
// Source: POS-kasir/internal/customers/repository (interfaces: Querier)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=mocks/mock_customers_repo.go -mock_names Querier=MockCustomerQuerier POS-kasir/internal/customers/repository Querier
//

// Package mocks is a generated GoMock package.
package mocks

import (
	repository "POS-kasir/internal/customers/repository"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCustomerQuerier is a mock of Querier interface.
type MockCustomerQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerQuerierMockRecorder
	isgomock struct{}
}

// MockCustomerQuerierMockRecorder is the mock recorder for MockCustomerQuerier.
type MockCustomerQuerierMockRecorder struct {
	mock *MockCustomerQuerier
}

// NewMockCustomerQuerier creates a new mock instance.
func NewMockCustomerQuerier(ctrl *gomock.Controller) *MockCustomerQuerier {
	mock := &MockCustomerQuerier{ctrl: ctrl}
	mock.recorder = &MockCustomerQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerQuerier) EXPECT() *MockCustomerQuerierMockRecorder {
	return m.recorder
}

// CountCustomers mocks base method.
func (m *MockCustomerQuerier) CountCustomers(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountCustomers", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountCustomers indicates an expected call of CountCustomers.
func (mr *MockCustomerQuerierMockRecorder) CountCustomers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountCustomers", reflect.TypeOf((*MockCustomerQuerier)(nil).CountCustomers), ctx)
}

// CreateCustomer mocks base method.
func (m *MockCustomerQuerier) CreateCustomer(ctx context.Context, arg repository.CreateCustomerParams) (repository.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCustomer", ctx, arg)
	ret0, _ := ret[0].(repository.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCustomer indicates an expected call of CreateCustomer.
func (mr *MockCustomerQuerierMockRecorder) CreateCustomer(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomer", reflect.TypeOf((*MockCustomerQuerier)(nil).CreateCustomer), ctx, arg)
}

// DeleteCustomer mocks base method.
func (m *MockCustomerQuerier) DeleteCustomer(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCustomer", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCustomer indicates an expected call of DeleteCustomer.
func (mr *MockCustomerQuerierMockRecorder) DeleteCustomer(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCustomer", reflect.TypeOf((*MockCustomerQuerier)(nil).DeleteCustomer), ctx, id)
}

// GetCustomerByID mocks base method.
func (m *MockCustomerQuerier) GetCustomerByID(ctx context.Context, id uuid.UUID) (repository.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomerByID", ctx, id)
	ret0, _ := ret[0].(repository.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomerByID indicates an expected call of GetCustomerByID.
func (mr *MockCustomerQuerierMockRecorder) GetCustomerByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerByID", reflect.TypeOf((*MockCustomerQuerier)(nil).GetCustomerByID), ctx, id)
}

// ListCustomers mocks base method.
func (m *MockCustomerQuerier) ListCustomers(ctx context.Context, arg repository.ListCustomersParams) ([]repository.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCustomers", ctx, arg)
	ret0, _ := ret[0].([]repository.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCustomers indicates an expected call of ListCustomers.
func (mr *MockCustomerQuerierMockRecorder) ListCustomers(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCustomers", reflect.TypeOf((*MockCustomerQuerier)(nil).ListCustomers), ctx, arg)
}

// UpdateCustomer mocks base method.
func (m *MockCustomerQuerier) UpdateCustomer(ctx context.Context, arg repository.UpdateCustomerParams) (repository.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCustomer", ctx, arg)
	ret0, _ := ret[0].(repository.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCustomer indicates an expected call of UpdateCustomer.
func (mr *MockCustomerQuerierMockRecorder) UpdateCustomer(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCustomer", reflect.TypeOf((*MockCustomerQuerier)(nil).UpdateCustomer), ctx, arg)
}
