// Code generated by MockGen. DO NOT EDIT.
// Source: POS-kasir/internal/orders (interfaces: IOrderService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_order_service.go -package=mocks POS-kasir/internal/orders IOrderService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	orders "POS-kasir/internal/orders"
	payment "POS-kasir/pkg/payment"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockIOrderService is a mock of IOrderService interface.
type MockIOrderService struct {
	ctrl     *gomock.Controller
	recorder *MockIOrderServiceMockRecorder
	isgomock struct{}
}

// MockIOrderServiceMockRecorder is the mock recorder for MockIOrderService.
type MockIOrderServiceMockRecorder struct {
	mock *MockIOrderService
}

// NewMockIOrderService creates a new mock instance.
func NewMockIOrderService(ctrl *gomock.Controller) *MockIOrderService {
	mock := &MockIOrderService{ctrl: ctrl}
	mock.recorder = &MockIOrderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIOrderService) EXPECT() *MockIOrderServiceMockRecorder {
	return m.recorder
}

// ApplyPromotion mocks base method.
func (m *MockIOrderService) ApplyPromotion(ctx context.Context, orderID uuid.UUID, req orders.ApplyPromotionRequest) (*orders.OrderDetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyPromotion", ctx, orderID, req)
	ret0, _ := ret[0].(*orders.OrderDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyPromotion indicates an expected call of ApplyPromotion.
func (mr *MockIOrderServiceMockRecorder) ApplyPromotion(ctx, orderID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyPromotion", reflect.TypeOf((*MockIOrderService)(nil).ApplyPromotion), ctx, orderID, req)
}

// CancelOrder mocks base method.
func (m *MockIOrderService) CancelOrder(ctx context.Context, orderID uuid.UUID, req orders.CancelOrderRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelOrder", ctx, orderID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelOrder indicates an expected call of CancelOrder.
func (mr *MockIOrderServiceMockRecorder) CancelOrder(ctx, orderID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelOrder", reflect.TypeOf((*MockIOrderService)(nil).CancelOrder), ctx, orderID, req)
}

// ConfirmManualPayment mocks base method.
func (m *MockIOrderService) ConfirmManualPayment(ctx context.Context, orderID uuid.UUID, req orders.ConfirmManualPaymentRequest) (*orders.OrderDetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmManualPayment", ctx, orderID, req)
	ret0, _ := ret[0].(*orders.OrderDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfirmManualPayment indicates an expected call of ConfirmManualPayment.
func (mr *MockIOrderServiceMockRecorder) ConfirmManualPayment(ctx, orderID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmManualPayment", reflect.TypeOf((*MockIOrderService)(nil).ConfirmManualPayment), ctx, orderID, req)
}

// CreateOrder mocks base method.
func (m *MockIOrderService) CreateOrder(ctx context.Context, req orders.CreateOrderRequest) (*orders.OrderDetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, req)
	ret0, _ := ret[0].(*orders.OrderDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockIOrderServiceMockRecorder) CreateOrder(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockIOrderService)(nil).CreateOrder), ctx, req)
}

// GetOrder mocks base method.
func (m *MockIOrderService) GetOrder(ctx context.Context, orderID uuid.UUID) (*orders.OrderDetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder", ctx, orderID)
	ret0, _ := ret[0].(*orders.OrderDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockIOrderServiceMockRecorder) GetOrder(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockIOrderService)(nil).GetOrder), ctx, orderID)
}

// HandleMidtransNotification mocks base method.
func (m *MockIOrderService) HandleMidtransNotification(ctx context.Context, payload payment.MidtransNotificationPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleMidtransNotification", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleMidtransNotification indicates an expected call of HandleMidtransNotification.
func (mr *MockIOrderServiceMockRecorder) HandleMidtransNotification(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleMidtransNotification", reflect.TypeOf((*MockIOrderService)(nil).HandleMidtransNotification), ctx, payload)
}

// InitiateMidtransPayment mocks base method.
func (m *MockIOrderService) InitiateMidtransPayment(ctx context.Context, orderID uuid.UUID) (*orders.MidtransPaymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiateMidtransPayment", ctx, orderID)
	ret0, _ := ret[0].(*orders.MidtransPaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitiateMidtransPayment indicates an expected call of InitiateMidtransPayment.
func (mr *MockIOrderServiceMockRecorder) InitiateMidtransPayment(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateMidtransPayment", reflect.TypeOf((*MockIOrderService)(nil).InitiateMidtransPayment), ctx, orderID)
}

// ListOrders mocks base method.
func (m *MockIOrderService) ListOrders(ctx context.Context, req orders.ListOrdersRequest) (*orders.PagedOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrders", ctx, req)
	ret0, _ := ret[0].(*orders.PagedOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrders indicates an expected call of ListOrders.
func (mr *MockIOrderServiceMockRecorder) ListOrders(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrders", reflect.TypeOf((*MockIOrderService)(nil).ListOrders), ctx, req)
}

// UpdateOperationalStatus mocks base method.
func (m *MockIOrderService) UpdateOperationalStatus(ctx context.Context, orderID uuid.UUID, req orders.UpdateOrderStatusRequest) (*orders.OrderDetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOperationalStatus", ctx, orderID, req)
	ret0, _ := ret[0].(*orders.OrderDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOperationalStatus indicates an expected call of UpdateOperationalStatus.
func (mr *MockIOrderServiceMockRecorder) UpdateOperationalStatus(ctx, orderID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOperationalStatus", reflect.TypeOf((*MockIOrderService)(nil).UpdateOperationalStatus), ctx, orderID, req)
}

// UpdateOrderItems mocks base method.
func (m *MockIOrderService) UpdateOrderItems(ctx context.Context, orderID uuid.UUID, req []orders.UpdateOrderItemRequest) (*orders.OrderDetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderItems", ctx, orderID, req)
	ret0, _ := ret[0].(*orders.OrderDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrderItems indicates an expected call of UpdateOrderItems.
func (mr *MockIOrderServiceMockRecorder) UpdateOrderItems(ctx, orderID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderItems", reflect.TypeOf((*MockIOrderService)(nil).UpdateOrderItems), ctx, orderID, req)
}
