// Code generated by MockGen. DO NOT EDIT.
// Source: POS-kasir/pkg/payment (interfaces: IMidtrans)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_midtrans.go -package=mocks POS-kasir/pkg/payment IMidtrans
//

// Package mocks is a generated GoMock package.
package mocks

import (
	payment "POS-kasir/pkg/payment"
	reflect "reflect"

	coreapi "github.com/midtrans/midtrans-go/coreapi"
	gomock "go.uber.org/mock/gomock"
)

// MockIMidtrans is a mock of IMidtrans interface.
type MockIMidtrans struct {
	ctrl     *gomock.Controller
	recorder *MockIMidtransMockRecorder
	isgomock struct{}
}

// MockIMidtransMockRecorder is the mock recorder for MockIMidtrans.
type MockIMidtransMockRecorder struct {
	mock *MockIMidtrans
}

// NewMockIMidtrans creates a new mock instance.
func NewMockIMidtrans(ctrl *gomock.Controller) *MockIMidtrans {
	mock := &MockIMidtrans{ctrl: ctrl}
	mock.recorder = &MockIMidtransMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMidtrans) EXPECT() *MockIMidtransMockRecorder {
	return m.recorder
}

// CancelTransaction mocks base method.
func (m *MockIMidtrans) CancelTransaction(orderID string) (*coreapi.CancelResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelTransaction", orderID)
	ret0, _ := ret[0].(*coreapi.CancelResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelTransaction indicates an expected call of CancelTransaction.
func (mr *MockIMidtransMockRecorder) CancelTransaction(orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelTransaction", reflect.TypeOf((*MockIMidtrans)(nil).CancelTransaction), orderID)
}

// CreateQRISCharge mocks base method.
func (m *MockIMidtrans) CreateQRISCharge(orderID string, amount int64) (*coreapi.ChargeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateQRISCharge", orderID, amount)
	ret0, _ := ret[0].(*coreapi.ChargeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateQRISCharge indicates an expected call of CreateQRISCharge.
func (mr *MockIMidtransMockRecorder) CreateQRISCharge(orderID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateQRISCharge", reflect.TypeOf((*MockIMidtrans)(nil).CreateQRISCharge), orderID, amount)
}

// GetQRISCharge mocks base method.
func (m *MockIMidtrans) GetQRISCharge(orderID string) (*coreapi.TransactionStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQRISCharge", orderID)
	ret0, _ := ret[0].(*coreapi.TransactionStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQRISCharge indicates an expected call of GetQRISCharge.
func (mr *MockIMidtransMockRecorder) GetQRISCharge(orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQRISCharge", reflect.TypeOf((*MockIMidtrans)(nil).GetQRISCharge), orderID)
}

// VerifyNotificationSignature mocks base method.
func (m *MockIMidtrans) VerifyNotificationSignature(payload payment.MidtransNotificationPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyNotificationSignature", payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyNotificationSignature indicates an expected call of VerifyNotificationSignature.
func (mr *MockIMidtransMockRecorder) VerifyNotificationSignature(payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyNotificationSignature", reflect.TypeOf((*MockIMidtrans)(nil).VerifyNotificationSignature), payload)
}
