// Code generated by MockGen. DO NOT EDIT.
// Source: POS-kasir/internal/settings (interfaces: ISettingsService)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=mocks/mock_settings_service.go -mock_names ISettingsService=MockISettingsService POS-kasir/internal/settings ISettingsService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	settings "POS-kasir/internal/settings"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockISettingsService is a mock of ISettingsService interface.
type MockISettingsService struct {
	ctrl     *gomock.Controller
	recorder *MockISettingsServiceMockRecorder
	isgomock struct{}
}

// MockISettingsServiceMockRecorder is the mock recorder for MockISettingsService.
type MockISettingsServiceMockRecorder struct {
	mock *MockISettingsService
}

// NewMockISettingsService creates a new mock instance.
func NewMockISettingsService(ctrl *gomock.Controller) *MockISettingsService {
	mock := &MockISettingsService{ctrl: ctrl}
	mock.recorder = &MockISettingsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISettingsService) EXPECT() *MockISettingsServiceMockRecorder {
	return m.recorder
}

// GetBranding mocks base method.
func (m *MockISettingsService) GetBranding(ctx context.Context) (*settings.BrandingSettingsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBranding", ctx)
	ret0, _ := ret[0].(*settings.BrandingSettingsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBranding indicates an expected call of GetBranding.
func (mr *MockISettingsServiceMockRecorder) GetBranding(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBranding", reflect.TypeOf((*MockISettingsService)(nil).GetBranding), ctx)
}

// GetPrinterSettings mocks base method.
func (m *MockISettingsService) GetPrinterSettings(ctx context.Context) (*settings.PrinterSettingsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrinterSettings", ctx)
	ret0, _ := ret[0].(*settings.PrinterSettingsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrinterSettings indicates an expected call of GetPrinterSettings.
func (mr *MockISettingsServiceMockRecorder) GetPrinterSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrinterSettings", reflect.TypeOf((*MockISettingsService)(nil).GetPrinterSettings), ctx)
}

// UpdateBranding mocks base method.
func (m *MockISettingsService) UpdateBranding(ctx context.Context, req settings.UpdateBrandingRequest) (*settings.BrandingSettingsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBranding", ctx, req)
	ret0, _ := ret[0].(*settings.BrandingSettingsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBranding indicates an expected call of UpdateBranding.
func (mr *MockISettingsServiceMockRecorder) UpdateBranding(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBranding", reflect.TypeOf((*MockISettingsService)(nil).UpdateBranding), ctx, req)
}

// UpdateLogo mocks base method.
func (m *MockISettingsService) UpdateLogo(ctx context.Context, data []byte, filename, contentType string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLogo", ctx, data, filename, contentType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateLogo indicates an expected call of UpdateLogo.
func (mr *MockISettingsServiceMockRecorder) UpdateLogo(ctx, data, filename, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLogo", reflect.TypeOf((*MockISettingsService)(nil).UpdateLogo), ctx, data, filename, contentType)
}

// UpdatePrinterSettings mocks base method.
func (m *MockISettingsService) UpdatePrinterSettings(ctx context.Context, req settings.UpdatePrinterSettingsRequest) (*settings.PrinterSettingsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePrinterSettings", ctx, req)
	ret0, _ := ret[0].(*settings.PrinterSettingsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePrinterSettings indicates an expected call of UpdatePrinterSettings.
func (mr *MockISettingsServiceMockRecorder) UpdatePrinterSettings(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePrinterSettings", reflect.TypeOf((*MockISettingsService)(nil).UpdatePrinterSettings), ctx, req)
}
