// Code generated by MockGen. DO NOT EDIT.
// Source: POS-kasir/internal/categories (interfaces: ICtgService)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/mock_categories_service.go POS-kasir/internal/categories ICtgService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "POS-kasir/internal/dto"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockICtgService is a mock of ICtgService interface.
type MockICtgService struct {
	ctrl     *gomock.Controller
	recorder *MockICtgServiceMockRecorder
	isgomock struct{}
}

// MockICtgServiceMockRecorder is the mock recorder for MockICtgService.
type MockICtgServiceMockRecorder struct {
	mock *MockICtgService
}

// NewMockICtgService creates a new mock instance.
func NewMockICtgService(ctrl *gomock.Controller) *MockICtgService {
	mock := &MockICtgService{ctrl: ctrl}
	mock.recorder = &MockICtgServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICtgService) EXPECT() *MockICtgServiceMockRecorder {
	return m.recorder
}

// CreateCategory mocks base method.
func (m *MockICtgService) CreateCategory(ctx context.Context, req dto.CreateCategoryRequest) (*dto.CategoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategory", ctx, req)
	ret0, _ := ret[0].(*dto.CategoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCategory indicates an expected call of CreateCategory.
func (mr *MockICtgServiceMockRecorder) CreateCategory(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategory", reflect.TypeOf((*MockICtgService)(nil).CreateCategory), ctx, req)
}

// DeleteCategory mocks base method.
func (m *MockICtgService) DeleteCategory(ctx context.Context, categoryID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategory", ctx, categoryID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCategory indicates an expected call of DeleteCategory.
func (mr *MockICtgServiceMockRecorder) DeleteCategory(ctx, categoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategory", reflect.TypeOf((*MockICtgService)(nil).DeleteCategory), ctx, categoryID)
}

// GetAllCategories mocks base method.
func (m *MockICtgService) GetAllCategories(ctx context.Context, req dto.ListCategoryRequest) ([]dto.CategoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCategories", ctx, req)
	ret0, _ := ret[0].([]dto.CategoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCategories indicates an expected call of GetAllCategories.
func (mr *MockICtgServiceMockRecorder) GetAllCategories(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCategories", reflect.TypeOf((*MockICtgService)(nil).GetAllCategories), ctx, req)
}

// GetCategoryByID mocks base method.
func (m *MockICtgService) GetCategoryByID(ctx context.Context, categoryID int32) (*dto.CategoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryByID", ctx, categoryID)
	ret0, _ := ret[0].(*dto.CategoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryByID indicates an expected call of GetCategoryByID.
func (mr *MockICtgServiceMockRecorder) GetCategoryByID(ctx, categoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryByID", reflect.TypeOf((*MockICtgService)(nil).GetCategoryByID), ctx, categoryID)
}

// GetCategoryWithProductCount mocks base method.
func (m *MockICtgService) GetCategoryWithProductCount(ctx context.Context) (*[]dto.CategoryWithCountResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryWithProductCount", ctx)
	ret0, _ := ret[0].(*[]dto.CategoryWithCountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryWithProductCount indicates an expected call of GetCategoryWithProductCount.
func (mr *MockICtgServiceMockRecorder) GetCategoryWithProductCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryWithProductCount", reflect.TypeOf((*MockICtgService)(nil).GetCategoryWithProductCount), ctx)
}

// UpdateCategory mocks base method.
func (m *MockICtgService) UpdateCategory(ctx context.Context, categoryID int32, req dto.CreateCategoryRequest) (*dto.CategoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCategory", ctx, categoryID, req)
	ret0, _ := ret[0].(*dto.CategoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCategory indicates an expected call of UpdateCategory.
func (mr *MockICtgServiceMockRecorder) UpdateCategory(ctx, categoryID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategory", reflect.TypeOf((*MockICtgService)(nil).UpdateCategory), ctx, categoryID, req)
}
