// Code generated by MockGen. DO NOT EDIT.
// Source: POS-kasir/internal/cancellation_reasons/repository (interfaces: Querier)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/mock_cancellation_reason_repo.go -mock_names Querier=MockCancellationReasonRepository POS-kasir/internal/cancellation_reasons/repository Querier
//

// Package mocks is a generated GoMock package.
package mocks

import (
	repository "POS-kasir/internal/cancellation_reasons/repository"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCancellationReasonRepository is a mock of Querier interface.
type MockCancellationReasonRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCancellationReasonRepositoryMockRecorder
	isgomock struct{}
}

// MockCancellationReasonRepositoryMockRecorder is the mock recorder for MockCancellationReasonRepository.
type MockCancellationReasonRepositoryMockRecorder struct {
	mock *MockCancellationReasonRepository
}

// NewMockCancellationReasonRepository creates a new mock instance.
func NewMockCancellationReasonRepository(ctrl *gomock.Controller) *MockCancellationReasonRepository {
	mock := &MockCancellationReasonRepository{ctrl: ctrl}
	mock.recorder = &MockCancellationReasonRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCancellationReasonRepository) EXPECT() *MockCancellationReasonRepositoryMockRecorder {
	return m.recorder
}

// CreateCancellationReason mocks base method.
func (m *MockCancellationReasonRepository) CreateCancellationReason(ctx context.Context, arg repository.CreateCancellationReasonParams) (repository.CancellationReason, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCancellationReason", ctx, arg)
	ret0, _ := ret[0].(repository.CancellationReason)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCancellationReason indicates an expected call of CreateCancellationReason.
func (mr *MockCancellationReasonRepositoryMockRecorder) CreateCancellationReason(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCancellationReason", reflect.TypeOf((*MockCancellationReasonRepository)(nil).CreateCancellationReason), ctx, arg)
}

// GetCancellationReasonByReason mocks base method.
func (m *MockCancellationReasonRepository) GetCancellationReasonByReason(ctx context.Context, reason string) (repository.CancellationReason, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCancellationReasonByReason", ctx, reason)
	ret0, _ := ret[0].(repository.CancellationReason)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCancellationReasonByReason indicates an expected call of GetCancellationReasonByReason.
func (mr *MockCancellationReasonRepositoryMockRecorder) GetCancellationReasonByReason(ctx, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCancellationReasonByReason", reflect.TypeOf((*MockCancellationReasonRepository)(nil).GetCancellationReasonByReason), ctx, reason)
}

// ListCancellationReasons mocks base method.
func (m *MockCancellationReasonRepository) ListCancellationReasons(ctx context.Context) ([]repository.CancellationReason, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCancellationReasons", ctx)
	ret0, _ := ret[0].([]repository.CancellationReason)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCancellationReasons indicates an expected call of ListCancellationReasons.
func (mr *MockCancellationReasonRepositoryMockRecorder) ListCancellationReasons(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCancellationReasons", reflect.TypeOf((*MockCancellationReasonRepository)(nil).ListCancellationReasons), ctx)
}
