// Code generated by MockGen. DO NOT EDIT.
// Source: POS-kasir/internal/activitylog/repository (interfaces: Querier)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/mock_activity_log_repo.go -mock_names Querier=MockActivityLogRepository POS-kasir/internal/activitylog/repository Querier
//

// Package mocks is a generated GoMock package.
package mocks

import (
	repository "POS-kasir/internal/activitylog/repository"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockActivityLogRepository is a mock of Querier interface.
type MockActivityLogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockActivityLogRepositoryMockRecorder
	isgomock struct{}
}

// MockActivityLogRepositoryMockRecorder is the mock recorder for MockActivityLogRepository.
type MockActivityLogRepositoryMockRecorder struct {
	mock *MockActivityLogRepository
}

// NewMockActivityLogRepository creates a new mock instance.
func NewMockActivityLogRepository(ctrl *gomock.Controller) *MockActivityLogRepository {
	mock := &MockActivityLogRepository{ctrl: ctrl}
	mock.recorder = &MockActivityLogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActivityLogRepository) EXPECT() *MockActivityLogRepositoryMockRecorder {
	return m.recorder
}

// CountActivityLogs mocks base method.
func (m *MockActivityLogRepository) CountActivityLogs(ctx context.Context, arg repository.CountActivityLogsParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActivityLogs", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActivityLogs indicates an expected call of CountActivityLogs.
func (mr *MockActivityLogRepositoryMockRecorder) CountActivityLogs(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActivityLogs", reflect.TypeOf((*MockActivityLogRepository)(nil).CountActivityLogs), ctx, arg)
}

// CreateActivityLog mocks base method.
func (m *MockActivityLogRepository) CreateActivityLog(ctx context.Context, arg repository.CreateActivityLogParams) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateActivityLog", ctx, arg)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateActivityLog indicates an expected call of CreateActivityLog.
func (mr *MockActivityLogRepositoryMockRecorder) CreateActivityLog(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateActivityLog", reflect.TypeOf((*MockActivityLogRepository)(nil).CreateActivityLog), ctx, arg)
}

// GetActivityLogs mocks base method.
func (m *MockActivityLogRepository) GetActivityLogs(ctx context.Context, arg repository.GetActivityLogsParams) ([]repository.GetActivityLogsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivityLogs", ctx, arg)
	ret0, _ := ret[0].([]repository.GetActivityLogsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivityLogs indicates an expected call of GetActivityLogs.
func (mr *MockActivityLogRepositoryMockRecorder) GetActivityLogs(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivityLogs", reflect.TypeOf((*MockActivityLogRepository)(nil).GetActivityLogs), ctx, arg)
}
