// Code generated by MockGen. DO NOT EDIT.
// Source: POS-kasir/internal/customers (interfaces: ICustomerService)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=mocks/mock_customer_service.go -mock_names ICustomerService=MockICustomerService POS-kasir/internal/customers ICustomerService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	customers "POS-kasir/internal/customers"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockICustomerService is a mock of ICustomerService interface.
type MockICustomerService struct {
	ctrl     *gomock.Controller
	recorder *MockICustomerServiceMockRecorder
	isgomock struct{}
}

// MockICustomerServiceMockRecorder is the mock recorder for MockICustomerService.
type MockICustomerServiceMockRecorder struct {
	mock *MockICustomerService
}

// NewMockICustomerService creates a new mock instance.
func NewMockICustomerService(ctrl *gomock.Controller) *MockICustomerService {
	mock := &MockICustomerService{ctrl: ctrl}
	mock.recorder = &MockICustomerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICustomerService) EXPECT() *MockICustomerServiceMockRecorder {
	return m.recorder
}

// CreateCustomer mocks base method.
func (m *MockICustomerService) CreateCustomer(ctx context.Context, req customers.CreateCustomerRequest) (*customers.CustomerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCustomer", ctx, req)
	ret0, _ := ret[0].(*customers.CustomerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCustomer indicates an expected call of CreateCustomer.
func (mr *MockICustomerServiceMockRecorder) CreateCustomer(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomer", reflect.TypeOf((*MockICustomerService)(nil).CreateCustomer), ctx, req)
}

// DeleteCustomer mocks base method.
func (m *MockICustomerService) DeleteCustomer(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCustomer", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCustomer indicates an expected call of DeleteCustomer.
func (mr *MockICustomerServiceMockRecorder) DeleteCustomer(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCustomer", reflect.TypeOf((*MockICustomerService)(nil).DeleteCustomer), ctx, id)
}

// GetCustomer mocks base method.
func (m *MockICustomerService) GetCustomer(ctx context.Context, id uuid.UUID) (*customers.CustomerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomer", ctx, id)
	ret0, _ := ret[0].(*customers.CustomerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomer indicates an expected call of GetCustomer.
func (mr *MockICustomerServiceMockRecorder) GetCustomer(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomer", reflect.TypeOf((*MockICustomerService)(nil).GetCustomer), ctx, id)
}

// ListCustomers mocks base method.
func (m *MockICustomerService) ListCustomers(ctx context.Context, req customers.ListCustomersRequest) (*customers.PagedCustomerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCustomers", ctx, req)
	ret0, _ := ret[0].(*customers.PagedCustomerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCustomers indicates an expected call of ListCustomers.
func (mr *MockICustomerServiceMockRecorder) ListCustomers(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCustomers", reflect.TypeOf((*MockICustomerService)(nil).ListCustomers), ctx, req)
}

// UpdateCustomer mocks base method.
func (m *MockICustomerService) UpdateCustomer(ctx context.Context, id uuid.UUID, req customers.UpdateCustomerRequest) (*customers.CustomerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCustomer", ctx, id, req)
	ret0, _ := ret[0].(*customers.CustomerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCustomer indicates an expected call of UpdateCustomer.
func (mr *MockICustomerServiceMockRecorder) UpdateCustomer(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCustomer", reflect.TypeOf((*MockICustomerService)(nil).UpdateCustomer), ctx, id, req)
}
