// Code generated by MockGen. DO NOT EDIT.
// Source: POS-kasir/internal/cancellation_reasons (interfaces: ICancellationReasonService)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/mock_cancellation_reasons_service.go POS-kasir/internal/cancellation_reasons ICancellationReasonService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "POS-kasir/internal/dto"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockICancellationReasonService is a mock of ICancellationReasonService interface.
type MockICancellationReasonService struct {
	ctrl     *gomock.Controller
	recorder *MockICancellationReasonServiceMockRecorder
	isgomock struct{}
}

// MockICancellationReasonServiceMockRecorder is the mock recorder for MockICancellationReasonService.
type MockICancellationReasonServiceMockRecorder struct {
	mock *MockICancellationReasonService
}

// NewMockICancellationReasonService creates a new mock instance.
func NewMockICancellationReasonService(ctrl *gomock.Controller) *MockICancellationReasonService {
	mock := &MockICancellationReasonService{ctrl: ctrl}
	mock.recorder = &MockICancellationReasonServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICancellationReasonService) EXPECT() *MockICancellationReasonServiceMockRecorder {
	return m.recorder
}

// ListCancellationReasons mocks base method.
func (m *MockICancellationReasonService) ListCancellationReasons(ctx context.Context) ([]dto.CancellationReasonResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCancellationReasons", ctx)
	ret0, _ := ret[0].([]dto.CancellationReasonResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCancellationReasons indicates an expected call of ListCancellationReasons.
func (mr *MockICancellationReasonServiceMockRecorder) ListCancellationReasons(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCancellationReasons", reflect.TypeOf((*MockICancellationReasonService)(nil).ListCancellationReasons), ctx)
}
