// Code generated by MockGen. DO NOT EDIT.
// Source: POS-kasir/pkg/cloudflare-r2 (interfaces: IR2)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/mock_r2.go POS-kasir/pkg/cloudflare-r2 IR2
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIR2 is a mock of IR2 interface.
type MockIR2 struct {
	ctrl     *gomock.Controller
	recorder *MockIR2MockRecorder
	isgomock struct{}
}

// MockIR2MockRecorder is the mock recorder for MockIR2.
type MockIR2MockRecorder struct {
	mock *MockIR2
}

// NewMockIR2 creates a new mock instance.
func NewMockIR2(ctrl *gomock.Controller) *MockIR2 {
	mock := &MockIR2{ctrl: ctrl}
	mock.recorder = &MockIR2MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIR2) EXPECT() *MockIR2MockRecorder {
	return m.recorder
}

// BucketExists mocks base method.
func (m *MockIR2) BucketExists(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BucketExists", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BucketExists indicates an expected call of BucketExists.
func (mr *MockIR2MockRecorder) BucketExists(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BucketExists", reflect.TypeOf((*MockIR2)(nil).BucketExists), ctx)
}

// GetFileShareLink mocks base method.
func (m *MockIR2) GetFileShareLink(ctx context.Context, objectName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileShareLink", ctx, objectName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileShareLink indicates an expected call of GetFileShareLink.
func (mr *MockIR2MockRecorder) GetFileShareLink(ctx, objectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileShareLink", reflect.TypeOf((*MockIR2)(nil).GetFileShareLink), ctx, objectName)
}

// UploadFile mocks base method.
func (m *MockIR2) UploadFile(ctx context.Context, objectName string, data []byte, contentType string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", ctx, objectName, data, contentType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockIR2MockRecorder) UploadFile(ctx, objectName, data, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockIR2)(nil).UploadFile), ctx, objectName, data, contentType)
}
