// Code generated by MockGen. DO NOT EDIT.
// Source: internal/promotions/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/promotions/service.go -destination=mocks/mock_promotion_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	promotions "POS-kasir/internal/promotions"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockIPromotionService is a mock of IPromotionService interface.
type MockIPromotionService struct {
	ctrl     *gomock.Controller
	recorder *MockIPromotionServiceMockRecorder
	isgomock struct{}
}

// MockIPromotionServiceMockRecorder is the mock recorder for MockIPromotionService.
type MockIPromotionServiceMockRecorder struct {
	mock *MockIPromotionService
}

// NewMockIPromotionService creates a new mock instance.
func NewMockIPromotionService(ctrl *gomock.Controller) *MockIPromotionService {
	mock := &MockIPromotionService{ctrl: ctrl}
	mock.recorder = &MockIPromotionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPromotionService) EXPECT() *MockIPromotionServiceMockRecorder {
	return m.recorder
}

// CreatePromotion mocks base method.
func (m *MockIPromotionService) CreatePromotion(ctx context.Context, req promotions.CreatePromotionRequest) (*promotions.PromotionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePromotion", ctx, req)
	ret0, _ := ret[0].(*promotions.PromotionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePromotion indicates an expected call of CreatePromotion.
func (mr *MockIPromotionServiceMockRecorder) CreatePromotion(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePromotion", reflect.TypeOf((*MockIPromotionService)(nil).CreatePromotion), ctx, req)
}

// DeletePromotion mocks base method.
func (m *MockIPromotionService) DeletePromotion(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePromotion", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePromotion indicates an expected call of DeletePromotion.
func (mr *MockIPromotionServiceMockRecorder) DeletePromotion(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePromotion", reflect.TypeOf((*MockIPromotionService)(nil).DeletePromotion), ctx, id)
}

// GetPromotion mocks base method.
func (m *MockIPromotionService) GetPromotion(ctx context.Context, id uuid.UUID) (*promotions.PromotionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPromotion", ctx, id)
	ret0, _ := ret[0].(*promotions.PromotionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPromotion indicates an expected call of GetPromotion.
func (mr *MockIPromotionServiceMockRecorder) GetPromotion(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPromotion", reflect.TypeOf((*MockIPromotionService)(nil).GetPromotion), ctx, id)
}

// ListPromotions mocks base method.
func (m *MockIPromotionService) ListPromotions(ctx context.Context, req promotions.ListPromotionsRequest) (*promotions.PagedPromotionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPromotions", ctx, req)
	ret0, _ := ret[0].(*promotions.PagedPromotionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPromotions indicates an expected call of ListPromotions.
func (mr *MockIPromotionServiceMockRecorder) ListPromotions(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPromotions", reflect.TypeOf((*MockIPromotionService)(nil).ListPromotions), ctx, req)
}

// RestorePromotion mocks base method.
func (m *MockIPromotionService) RestorePromotion(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestorePromotion", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestorePromotion indicates an expected call of RestorePromotion.
func (mr *MockIPromotionServiceMockRecorder) RestorePromotion(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestorePromotion", reflect.TypeOf((*MockIPromotionService)(nil).RestorePromotion), ctx, id)
}

// UpdatePromotion mocks base method.
func (m *MockIPromotionService) UpdatePromotion(ctx context.Context, id uuid.UUID, req promotions.UpdatePromotionRequest) (*promotions.PromotionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePromotion", ctx, id, req)
	ret0, _ := ret[0].(*promotions.PromotionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePromotion indicates an expected call of UpdatePromotion.
func (mr *MockIPromotionServiceMockRecorder) UpdatePromotion(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePromotion", reflect.TypeOf((*MockIPromotionService)(nil).UpdatePromotion), ctx, id, req)
}
