// Code generated by MockGen. DO NOT EDIT.
// Source: POS-kasir/internal/orders/repository (interfaces: Querier)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_orders_repo.go -package=mocks POS-kasir/internal/orders/repository Querier
//

// Package mocks is a generated GoMock package.
package mocks

import (
	repository "POS-kasir/internal/orders/repository"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderQuerier is a mock of Querier interface.
type MockOrderQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockOrderQuerierMockRecorder
	isgomock struct{}
}

// MockOrderQuerierMockRecorder is the mock recorder for MockOrderQuerier.
type MockOrderQuerierMockRecorder struct {
	mock *MockOrderQuerier
}

// NewMockOrderQuerier creates a new mock instance.
func NewMockOrderQuerier(ctrl *gomock.Controller) *MockOrderQuerier {
	mock := &MockOrderQuerier{ctrl: ctrl}
	mock.recorder = &MockOrderQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderQuerier) EXPECT() *MockOrderQuerierMockRecorder {
	return m.recorder
}

// AddProductStock mocks base method.
func (m *MockOrderQuerier) AddProductStock(ctx context.Context, arg repository.AddProductStockParams) (repository.AddProductStockRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProductStock", ctx, arg)
	ret0, _ := ret[0].(repository.AddProductStockRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddProductStock indicates an expected call of AddProductStock.
func (mr *MockOrderQuerierMockRecorder) AddProductStock(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProductStock", reflect.TypeOf((*MockOrderQuerier)(nil).AddProductStock), ctx, arg)
}

// BatchCreateOrderItemOptions mocks base method.
func (m *MockOrderQuerier) BatchCreateOrderItemOptions(ctx context.Context, arg []repository.BatchCreateOrderItemOptionsParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreateOrderItemOptions", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchCreateOrderItemOptions indicates an expected call of BatchCreateOrderItemOptions.
func (mr *MockOrderQuerierMockRecorder) BatchCreateOrderItemOptions(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreateOrderItemOptions", reflect.TypeOf((*MockOrderQuerier)(nil).BatchCreateOrderItemOptions), ctx, arg)
}

// BatchCreateOrderItems mocks base method.
func (m *MockOrderQuerier) BatchCreateOrderItems(ctx context.Context, arg repository.BatchCreateOrderItemsParams) ([]repository.OrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreateOrderItems", ctx, arg)
	ret0, _ := ret[0].([]repository.OrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchCreateOrderItems indicates an expected call of BatchCreateOrderItems.
func (mr *MockOrderQuerierMockRecorder) BatchCreateOrderItems(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreateOrderItems", reflect.TypeOf((*MockOrderQuerier)(nil).BatchCreateOrderItems), ctx, arg)
}

// BatchDecreaseProductStock mocks base method.
func (m *MockOrderQuerier) BatchDecreaseProductStock(ctx context.Context, arg repository.BatchDecreaseProductStockParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDecreaseProductStock", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDecreaseProductStock indicates an expected call of BatchDecreaseProductStock.
func (mr *MockOrderQuerierMockRecorder) BatchDecreaseProductStock(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDecreaseProductStock", reflect.TypeOf((*MockOrderQuerier)(nil).BatchDecreaseProductStock), ctx, arg)
}

// CancelOrder mocks base method.
func (m *MockOrderQuerier) CancelOrder(ctx context.Context, arg repository.CancelOrderParams) (repository.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelOrder", ctx, arg)
	ret0, _ := ret[0].(repository.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelOrder indicates an expected call of CancelOrder.
func (mr *MockOrderQuerierMockRecorder) CancelOrder(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelOrder", reflect.TypeOf((*MockOrderQuerier)(nil).CancelOrder), ctx, arg)
}

// CountOrders mocks base method.
func (m *MockOrderQuerier) CountOrders(ctx context.Context, arg repository.CountOrdersParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountOrders", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountOrders indicates an expected call of CountOrders.
func (mr *MockOrderQuerierMockRecorder) CountOrders(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountOrders", reflect.TypeOf((*MockOrderQuerier)(nil).CountOrders), ctx, arg)
}

// CreateOrder mocks base method.
func (m *MockOrderQuerier) CreateOrder(ctx context.Context, arg repository.CreateOrderParams) (repository.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, arg)
	ret0, _ := ret[0].(repository.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockOrderQuerierMockRecorder) CreateOrder(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockOrderQuerier)(nil).CreateOrder), ctx, arg)
}

// CreateOrderItem mocks base method.
func (m *MockOrderQuerier) CreateOrderItem(ctx context.Context, arg repository.CreateOrderItemParams) (repository.OrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrderItem", ctx, arg)
	ret0, _ := ret[0].(repository.OrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrderItem indicates an expected call of CreateOrderItem.
func (mr *MockOrderQuerierMockRecorder) CreateOrderItem(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrderItem", reflect.TypeOf((*MockOrderQuerier)(nil).CreateOrderItem), ctx, arg)
}

// CreateOrderItemOption mocks base method.
func (m *MockOrderQuerier) CreateOrderItemOption(ctx context.Context, arg repository.CreateOrderItemOptionParams) (repository.OrderItemOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrderItemOption", ctx, arg)
	ret0, _ := ret[0].(repository.OrderItemOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrderItemOption indicates an expected call of CreateOrderItemOption.
func (mr *MockOrderQuerierMockRecorder) CreateOrderItemOption(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrderItemOption", reflect.TypeOf((*MockOrderQuerier)(nil).CreateOrderItemOption), ctx, arg)
}

// CreateStockHistory mocks base method.
func (m *MockOrderQuerier) CreateStockHistory(ctx context.Context, arg repository.CreateStockHistoryParams) (repository.StockHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStockHistory", ctx, arg)
	ret0, _ := ret[0].(repository.StockHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStockHistory indicates an expected call of CreateStockHistory.
func (mr *MockOrderQuerierMockRecorder) CreateStockHistory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStockHistory", reflect.TypeOf((*MockOrderQuerier)(nil).CreateStockHistory), ctx, arg)
}

// DecreaseProductStock mocks base method.
func (m *MockOrderQuerier) DecreaseProductStock(ctx context.Context, arg repository.DecreaseProductStockParams) (repository.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecreaseProductStock", ctx, arg)
	ret0, _ := ret[0].(repository.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecreaseProductStock indicates an expected call of DecreaseProductStock.
func (mr *MockOrderQuerierMockRecorder) DecreaseProductStock(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecreaseProductStock", reflect.TypeOf((*MockOrderQuerier)(nil).DecreaseProductStock), ctx, arg)
}

// DeleteOrderItem mocks base method.
func (m *MockOrderQuerier) DeleteOrderItem(ctx context.Context, arg repository.DeleteOrderItemParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrderItem", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrderItem indicates an expected call of DeleteOrderItem.
func (mr *MockOrderQuerierMockRecorder) DeleteOrderItem(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrderItem", reflect.TypeOf((*MockOrderQuerier)(nil).DeleteOrderItem), ctx, arg)
}

// DeleteOrderItemOptionsByOrderItemID mocks base method.
func (m *MockOrderQuerier) DeleteOrderItemOptionsByOrderItemID(ctx context.Context, orderItemID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrderItemOptionsByOrderItemID", ctx, orderItemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrderItemOptionsByOrderItemID indicates an expected call of DeleteOrderItemOptionsByOrderItemID.
func (mr *MockOrderQuerierMockRecorder) DeleteOrderItemOptionsByOrderItemID(ctx, orderItemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrderItemOptionsByOrderItemID", reflect.TypeOf((*MockOrderQuerier)(nil).DeleteOrderItemOptionsByOrderItemID), ctx, orderItemID)
}

// DeleteOrderItemsByOrderID mocks base method.
func (m *MockOrderQuerier) DeleteOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrderItemsByOrderID", ctx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrderItemsByOrderID indicates an expected call of DeleteOrderItemsByOrderID.
func (mr *MockOrderQuerierMockRecorder) DeleteOrderItemsByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrderItemsByOrderID", reflect.TypeOf((*MockOrderQuerier)(nil).DeleteOrderItemsByOrderID), ctx, orderID)
}

// GetOptionsForProducts mocks base method.
func (m *MockOrderQuerier) GetOptionsForProducts(ctx context.Context, dollar_1 []uuid.UUID) ([]repository.ProductOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOptionsForProducts", ctx, dollar_1)
	ret0, _ := ret[0].([]repository.ProductOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOptionsForProducts indicates an expected call of GetOptionsForProducts.
func (mr *MockOrderQuerierMockRecorder) GetOptionsForProducts(ctx, dollar_1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOptionsForProducts", reflect.TypeOf((*MockOrderQuerier)(nil).GetOptionsForProducts), ctx, dollar_1)
}

// GetOrderByGatewayRef mocks base method.
func (m *MockOrderQuerier) GetOrderByGatewayRef(ctx context.Context, paymentGatewayReference *string) (repository.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByGatewayRef", ctx, paymentGatewayReference)
	ret0, _ := ret[0].(repository.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByGatewayRef indicates an expected call of GetOrderByGatewayRef.
func (mr *MockOrderQuerierMockRecorder) GetOrderByGatewayRef(ctx, paymentGatewayReference any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByGatewayRef", reflect.TypeOf((*MockOrderQuerier)(nil).GetOrderByGatewayRef), ctx, paymentGatewayReference)
}

// GetOrderForUpdate mocks base method.
func (m *MockOrderQuerier) GetOrderForUpdate(ctx context.Context, id uuid.UUID) (repository.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderForUpdate", ctx, id)
	ret0, _ := ret[0].(repository.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderForUpdate indicates an expected call of GetOrderForUpdate.
func (mr *MockOrderQuerierMockRecorder) GetOrderForUpdate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderForUpdate", reflect.TypeOf((*MockOrderQuerier)(nil).GetOrderForUpdate), ctx, id)
}

// GetOrderItem mocks base method.
func (m *MockOrderQuerier) GetOrderItem(ctx context.Context, arg repository.GetOrderItemParams) (repository.OrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderItem", ctx, arg)
	ret0, _ := ret[0].(repository.OrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderItem indicates an expected call of GetOrderItem.
func (mr *MockOrderQuerierMockRecorder) GetOrderItem(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderItem", reflect.TypeOf((*MockOrderQuerier)(nil).GetOrderItem), ctx, arg)
}

// GetOrderItemsByOrderID mocks base method.
func (m *MockOrderQuerier) GetOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]repository.OrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderItemsByOrderID", ctx, orderID)
	ret0, _ := ret[0].([]repository.OrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderItemsByOrderID indicates an expected call of GetOrderItemsByOrderID.
func (mr *MockOrderQuerierMockRecorder) GetOrderItemsByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderItemsByOrderID", reflect.TypeOf((*MockOrderQuerier)(nil).GetOrderItemsByOrderID), ctx, orderID)
}

// GetOrderWithDetails mocks base method.
func (m *MockOrderQuerier) GetOrderWithDetails(ctx context.Context, id uuid.UUID) (repository.GetOrderWithDetailsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderWithDetails", ctx, id)
	ret0, _ := ret[0].(repository.GetOrderWithDetailsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderWithDetails indicates an expected call of GetOrderWithDetails.
func (mr *MockOrderQuerierMockRecorder) GetOrderWithDetails(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderWithDetails", reflect.TypeOf((*MockOrderQuerier)(nil).GetOrderWithDetails), ctx, id)
}

// GetProductByID mocks base method.
func (m *MockOrderQuerier) GetProductByID(ctx context.Context, id uuid.UUID) (repository.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductByID", ctx, id)
	ret0, _ := ret[0].(repository.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductByID indicates an expected call of GetProductByID.
func (mr *MockOrderQuerierMockRecorder) GetProductByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductByID", reflect.TypeOf((*MockOrderQuerier)(nil).GetProductByID), ctx, id)
}

// GetProductOptionsByIDs mocks base method.
func (m *MockOrderQuerier) GetProductOptionsByIDs(ctx context.Context, ids []uuid.UUID) ([]repository.ProductOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductOptionsByIDs", ctx, ids)
	ret0, _ := ret[0].([]repository.ProductOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductOptionsByIDs indicates an expected call of GetProductOptionsByIDs.
func (mr *MockOrderQuerierMockRecorder) GetProductOptionsByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductOptionsByIDs", reflect.TypeOf((*MockOrderQuerier)(nil).GetProductOptionsByIDs), ctx, ids)
}

// GetProductsByIDs mocks base method.
func (m *MockOrderQuerier) GetProductsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]repository.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductsByIDs", ctx, dollar_1)
	ret0, _ := ret[0].([]repository.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductsByIDs indicates an expected call of GetProductsByIDs.
func (mr *MockOrderQuerierMockRecorder) GetProductsByIDs(ctx, dollar_1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductsByIDs", reflect.TypeOf((*MockOrderQuerier)(nil).GetProductsByIDs), ctx, dollar_1)
}

// GetProductsForUpdate mocks base method.
func (m *MockOrderQuerier) GetProductsForUpdate(ctx context.Context, dollar_1 []uuid.UUID) ([]repository.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductsForUpdate", ctx, dollar_1)
	ret0, _ := ret[0].([]repository.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductsForUpdate indicates an expected call of GetProductsForUpdate.
func (mr *MockOrderQuerierMockRecorder) GetProductsForUpdate(ctx, dollar_1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductsForUpdate", reflect.TypeOf((*MockOrderQuerier)(nil).GetProductsForUpdate), ctx, dollar_1)
}

// GetPromotionByID mocks base method.
func (m *MockOrderQuerier) GetPromotionByID(ctx context.Context, id uuid.UUID) (repository.Promotion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPromotionByID", ctx, id)
	ret0, _ := ret[0].(repository.Promotion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPromotionByID indicates an expected call of GetPromotionByID.
func (mr *MockOrderQuerierMockRecorder) GetPromotionByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPromotionByID", reflect.TypeOf((*MockOrderQuerier)(nil).GetPromotionByID), ctx, id)
}

// GetPromotionRules mocks base method.
func (m *MockOrderQuerier) GetPromotionRules(ctx context.Context, promotionID uuid.UUID) ([]repository.PromotionRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPromotionRules", ctx, promotionID)
	ret0, _ := ret[0].([]repository.PromotionRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPromotionRules indicates an expected call of GetPromotionRules.
func (mr *MockOrderQuerierMockRecorder) GetPromotionRules(ctx, promotionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPromotionRules", reflect.TypeOf((*MockOrderQuerier)(nil).GetPromotionRules), ctx, promotionID)
}

// GetPromotionTargets mocks base method.
func (m *MockOrderQuerier) GetPromotionTargets(ctx context.Context, promotionID uuid.UUID) ([]repository.PromotionTarget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPromotionTargets", ctx, promotionID)
	ret0, _ := ret[0].([]repository.PromotionTarget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPromotionTargets indicates an expected call of GetPromotionTargets.
func (mr *MockOrderQuerierMockRecorder) GetPromotionTargets(ctx, promotionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPromotionTargets", reflect.TypeOf((*MockOrderQuerier)(nil).GetPromotionTargets), ctx, promotionID)
}

// ListOrders mocks base method.
func (m *MockOrderQuerier) ListOrders(ctx context.Context, arg repository.ListOrdersParams) ([]repository.ListOrdersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrders", ctx, arg)
	ret0, _ := ret[0].([]repository.ListOrdersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrders indicates an expected call of ListOrders.
func (mr *MockOrderQuerierMockRecorder) ListOrders(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrders", reflect.TypeOf((*MockOrderQuerier)(nil).ListOrders), ctx, arg)
}

// UpdateOrderAppliedPromotion mocks base method.
func (m *MockOrderQuerier) UpdateOrderAppliedPromotion(ctx context.Context, arg repository.UpdateOrderAppliedPromotionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderAppliedPromotion", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderAppliedPromotion indicates an expected call of UpdateOrderAppliedPromotion.
func (mr *MockOrderQuerierMockRecorder) UpdateOrderAppliedPromotion(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderAppliedPromotion", reflect.TypeOf((*MockOrderQuerier)(nil).UpdateOrderAppliedPromotion), ctx, arg)
}

// UpdateOrderItemQuantity mocks base method.
func (m *MockOrderQuerier) UpdateOrderItemQuantity(ctx context.Context, arg repository.UpdateOrderItemQuantityParams) (repository.OrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderItemQuantity", ctx, arg)
	ret0, _ := ret[0].(repository.OrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrderItemQuantity indicates an expected call of UpdateOrderItemQuantity.
func (mr *MockOrderQuerierMockRecorder) UpdateOrderItemQuantity(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderItemQuantity", reflect.TypeOf((*MockOrderQuerier)(nil).UpdateOrderItemQuantity), ctx, arg)
}

// UpdateOrderManualPayment mocks base method.
func (m *MockOrderQuerier) UpdateOrderManualPayment(ctx context.Context, arg repository.UpdateOrderManualPaymentParams) (repository.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderManualPayment", ctx, arg)
	ret0, _ := ret[0].(repository.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrderManualPayment indicates an expected call of UpdateOrderManualPayment.
func (mr *MockOrderQuerierMockRecorder) UpdateOrderManualPayment(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderManualPayment", reflect.TypeOf((*MockOrderQuerier)(nil).UpdateOrderManualPayment), ctx, arg)
}

// UpdateOrderPaymentInfo mocks base method.
func (m *MockOrderQuerier) UpdateOrderPaymentInfo(ctx context.Context, arg repository.UpdateOrderPaymentInfoParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderPaymentInfo", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderPaymentInfo indicates an expected call of UpdateOrderPaymentInfo.
func (mr *MockOrderQuerierMockRecorder) UpdateOrderPaymentInfo(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderPaymentInfo", reflect.TypeOf((*MockOrderQuerier)(nil).UpdateOrderPaymentInfo), ctx, arg)
}

// UpdateOrderPaymentUrl mocks base method.
func (m *MockOrderQuerier) UpdateOrderPaymentUrl(ctx context.Context, arg repository.UpdateOrderPaymentUrlParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderPaymentUrl", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderPaymentUrl indicates an expected call of UpdateOrderPaymentUrl.
func (mr *MockOrderQuerierMockRecorder) UpdateOrderPaymentUrl(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderPaymentUrl", reflect.TypeOf((*MockOrderQuerier)(nil).UpdateOrderPaymentUrl), ctx, arg)
}

// UpdateOrderStatus mocks base method.
func (m *MockOrderQuerier) UpdateOrderStatus(ctx context.Context, arg repository.UpdateOrderStatusParams) (repository.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", ctx, arg)
	ret0, _ := ret[0].(repository.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockOrderQuerierMockRecorder) UpdateOrderStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockOrderQuerier)(nil).UpdateOrderStatus), ctx, arg)
}

// UpdateOrderStatusByGatewayRef mocks base method.
func (m *MockOrderQuerier) UpdateOrderStatusByGatewayRef(ctx context.Context, arg repository.UpdateOrderStatusByGatewayRefParams) (repository.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatusByGatewayRef", ctx, arg)
	ret0, _ := ret[0].(repository.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrderStatusByGatewayRef indicates an expected call of UpdateOrderStatusByGatewayRef.
func (mr *MockOrderQuerierMockRecorder) UpdateOrderStatusByGatewayRef(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatusByGatewayRef", reflect.TypeOf((*MockOrderQuerier)(nil).UpdateOrderStatusByGatewayRef), ctx, arg)
}

// UpdateOrderTotals mocks base method.
func (m *MockOrderQuerier) UpdateOrderTotals(ctx context.Context, arg repository.UpdateOrderTotalsParams) (repository.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderTotals", ctx, arg)
	ret0, _ := ret[0].(repository.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrderTotals indicates an expected call of UpdateOrderTotals.
func (mr *MockOrderQuerierMockRecorder) UpdateOrderTotals(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderTotals", reflect.TypeOf((*MockOrderQuerier)(nil).UpdateOrderTotals), ctx, arg)
}
