// Code generated by MockGen. DO NOT EDIT.
// Source: POS-kasir/internal/settings/repository (interfaces: Querier)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=mocks/mock_settings_repo.go -mock_names Querier=MockSettingsQuerier POS-kasir/internal/settings/repository Querier
//

// Package mocks is a generated GoMock package.
package mocks

import (
	repository "POS-kasir/internal/settings/repository"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSettingsQuerier is a mock of Querier interface.
type MockSettingsQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockSettingsQuerierMockRecorder
	isgomock struct{}
}

// MockSettingsQuerierMockRecorder is the mock recorder for MockSettingsQuerier.
type MockSettingsQuerierMockRecorder struct {
	mock *MockSettingsQuerier
}

// NewMockSettingsQuerier creates a new mock instance.
func NewMockSettingsQuerier(ctrl *gomock.Controller) *MockSettingsQuerier {
	mock := &MockSettingsQuerier{ctrl: ctrl}
	mock.recorder = &MockSettingsQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettingsQuerier) EXPECT() *MockSettingsQuerierMockRecorder {
	return m.recorder
}

// GetSettingByKey mocks base method.
func (m *MockSettingsQuerier) GetSettingByKey(ctx context.Context, key string) (repository.Setting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSettingByKey", ctx, key)
	ret0, _ := ret[0].(repository.Setting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSettingByKey indicates an expected call of GetSettingByKey.
func (mr *MockSettingsQuerierMockRecorder) GetSettingByKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSettingByKey", reflect.TypeOf((*MockSettingsQuerier)(nil).GetSettingByKey), ctx, key)
}

// GetSettings mocks base method.
func (m *MockSettingsQuerier) GetSettings(ctx context.Context) ([]repository.Setting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSettings", ctx)
	ret0, _ := ret[0].([]repository.Setting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSettings indicates an expected call of GetSettings.
func (mr *MockSettingsQuerierMockRecorder) GetSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSettings", reflect.TypeOf((*MockSettingsQuerier)(nil).GetSettings), ctx)
}

// UpdateSetting mocks base method.
func (m *MockSettingsQuerier) UpdateSetting(ctx context.Context, arg repository.UpdateSettingParams) (repository.Setting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSetting", ctx, arg)
	ret0, _ := ret[0].(repository.Setting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSetting indicates an expected call of UpdateSetting.
func (mr *MockSettingsQuerierMockRecorder) UpdateSetting(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSetting", reflect.TypeOf((*MockSettingsQuerier)(nil).UpdateSetting), ctx, arg)
}

// UpsertSetting mocks base method.
func (m *MockSettingsQuerier) UpsertSetting(ctx context.Context, arg repository.UpsertSettingParams) (repository.Setting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertSetting", ctx, arg)
	ret0, _ := ret[0].(repository.Setting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertSetting indicates an expected call of UpsertSetting.
func (mr *MockSettingsQuerierMockRecorder) UpsertSetting(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertSetting", reflect.TypeOf((*MockSettingsQuerier)(nil).UpsertSetting), ctx, arg)
}
