// Code generated by MockGen. DO NOT EDIT.
// Source: internal/products/image_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/products/image_repository.go -destination=mocks/mock_products_image_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIProductImageRepository is a mock of IProductImageRepository interface.
type MockIProductImageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIProductImageRepositoryMockRecorder
	isgomock struct{}
}

// MockIProductImageRepositoryMockRecorder is the mock recorder for MockIProductImageRepository.
type MockIProductImageRepositoryMockRecorder struct {
	mock *MockIProductImageRepository
}

// NewMockIProductImageRepository creates a new mock instance.
func NewMockIProductImageRepository(ctrl *gomock.Controller) *MockIProductImageRepository {
	mock := &MockIProductImageRepository{ctrl: ctrl}
	mock.recorder = &MockIProductImageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIProductImageRepository) EXPECT() *MockIProductImageRepositoryMockRecorder {
	return m.recorder
}

// PrdImageLink mocks base method.
func (m *MockIProductImageRepository) PrdImageLink(ctx context.Context, prdID, image string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrdImageLink", ctx, prdID, image)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrdImageLink indicates an expected call of PrdImageLink.
func (mr *MockIProductImageRepositoryMockRecorder) PrdImageLink(ctx, prdID, image any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrdImageLink", reflect.TypeOf((*MockIProductImageRepository)(nil).PrdImageLink), ctx, prdID, image)
}

// UploadImage mocks base method.
func (m *MockIProductImageRepository) UploadImage(ctx context.Context, filename string, data []byte) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadImage", ctx, filename, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadImage indicates an expected call of UploadImage.
func (mr *MockIProductImageRepositoryMockRecorder) UploadImage(ctx, filename, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadImage", reflect.TypeOf((*MockIProductImageRepository)(nil).UploadImage), ctx, filename, data)
}
