// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Menambahkan stok kembali ke sebuah produk (digunakan saat pesanan dibatalkan).
	AddProductStock(ctx context.Context, arg AddProductStockParams) (AddProductStockRow, error)
	BatchCreateOrderItemOptions(ctx context.Context, arg []BatchCreateOrderItemOptionsParams) (int64, error)
	// Memasukkan banyak item sekaligus menggunakan array (Bulk Insert).
	BatchCreateOrderItems(ctx context.Context, arg BatchCreateOrderItemsParams) ([]OrderItem, error)
	// Mengurangi stok banyak produk sekaligus berdasarkan pasangan ID dan Qty.
	BatchDecreaseProductStock(ctx context.Context, arg BatchDecreaseProductStockParams) error
	// Mengubah status pesanan menjadi 'cancelled' dan mencatat alasannya.
	// Hanya bisa membatalkan pesanan yang statusnya 'open'.
	CancelOrder(ctx context.Context, arg CancelOrderParams) (Order, error)
	// Menghitung total pesanan dengan filter.
	CountOrders(ctx context.Context, arg CountOrdersParams) (int64, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	// Menambahkan satu item produk ke dalam pesanan.
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	// Menambahkan satu varian/opsi ke dalam sebuah order item.
	CreateOrderItemOption(ctx context.Context, arg CreateOrderItemOptionParams) (OrderItemOption, error)
	CreateStockHistory(ctx context.Context, arg CreateStockHistoryParams) (StockHistory, error)
	// Mengurangi stok produk.
	DecreaseProductStock(ctx context.Context, arg DecreaseProductStockParams) (Product, error)
	// Menghapus satu item dari pesanan.
	DeleteOrderItem(ctx context.Context, arg DeleteOrderItemParams) error
	DeleteOrderItemOptionsByOrderItemID(ctx context.Context, orderItemID uuid.UUID) error
	DeleteOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) error
	// Mengambil semua varian untuk beberapa produk.
	GetOptionsForProducts(ctx context.Context, dollar_1 []uuid.UUID) ([]ProductOption, error)
	// Mengambil pesanan berdasarkan referensi dari payment gateway.
	GetOrderByGatewayRef(ctx context.Context, paymentGatewayReference *string) (Order, error)
	// Mengambil satu pesanan dan mengunci barisnya untuk pembaruan (mencegah race condition).
	// Penting untuk digunakan di dalam transaksi sebelum mengupdate total.
	GetOrderForUpdate(ctx context.Context, id uuid.UUID) (Order, error)
	// Mengambil satu item pesanan untuk validasi sebelum update/delete.
	GetOrderItem(ctx context.Context, arg GetOrderItemParams) (OrderItem, error)
	// Mengambil semua item dari sebuah pesanan untuk menghitung ulang total.
	GetOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error)
	// Mengambil detail lengkap pesanan, termasuk item dan opsinya dalam format JSON.
	GetOrderWithDetails(ctx context.Context, id uuid.UUID) (GetOrderWithDetailsRow, error)
	GetProductByID(ctx context.Context, id uuid.UUID) (Product, error)
	GetProductOptionsByIDs(ctx context.Context, ids []uuid.UUID) ([]ProductOption, error)
	// Mengambil beberapa produk berdasarkan array ID. Ini untuk menghindari N+1 query.
	GetProductsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Product, error)
	// Mengambil produk sekaligus mengunci barisnya (Row-Level Locking).
	// Transaksi lain yang mencoba update produk ini harus menunggu sampai transaksi ini selesai.
	GetProductsForUpdate(ctx context.Context, dollar_1 []uuid.UUID) ([]Product, error)
	GetPromotionByID(ctx context.Context, id uuid.UUID) (Promotion, error)
	GetPromotionRules(ctx context.Context, promotionID uuid.UUID) ([]PromotionRule, error)
	GetPromotionTargets(ctx context.Context, promotionID uuid.UUID) ([]PromotionTarget, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]ListOrdersRow, error)
	UpdateOrderAppliedPromotion(ctx context.Context, arg UpdateOrderAppliedPromotionParams) error
	// Update qty dan subtotal. Penting: Tambahkan validasi stok/constraint di level aplikasi
	// atau pastikan trigger handle pengurangan stok jika qty bertambah.
	UpdateOrderItemQuantity(ctx context.Context, arg UpdateOrderItemQuantityParams) (OrderItem, error)
	// Memperbarui pesanan untuk pembayaran manual (tunai, dll.) dan mengubah status menjadi 'paid'.
	// Hanya bisa memproses pesanan yang statusnya 'open'.
	UpdateOrderManualPayment(ctx context.Context, arg UpdateOrderManualPaymentParams) (Order, error)
	// Menyimpan referensi pembayaran dari payment gateway dan metode pembayaran.
	UpdateOrderPaymentInfo(ctx context.Context, arg UpdateOrderPaymentInfoParams) error
	// Menyimpan URL pembayaran (QR string atau deep link) dan token.
	UpdateOrderPaymentUrl(ctx context.Context, arg UpdateOrderPaymentUrlParams) error
	// Memperbarui status operasional sebuah pesanan.
	// Validasi transisi status dilakukan di level aplikasi/service.
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	// Memperbarui status pesanan berdasarkan referensi dari payment gateway (digunakan oleh webhook).
	UpdateOrderStatusByGatewayRef(ctx context.Context, arg UpdateOrderStatusByGatewayRefParams) (Order, error)
	// Memperbarui total harga, diskon, dan total bersih dari sebuah pesanan.
	UpdateOrderTotals(ctx context.Context, arg UpdateOrderTotalsParams) (Order, error)
}

var _ Querier = (*Queries)(nil)
