// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CheckCategoryExists(ctx context.Context, id int32) (bool, error)
	CountDeletedProducts(ctx context.Context, arg CountDeletedProductsParams) (int64, error)
	// Counts total products for pagination, respecting filters.
	CountProducts(ctx context.Context, arg CountProductsParams) (int64, error)
	CountStockHistoryByProduct(ctx context.Context, productID uuid.UUID) (int64, error)
	// Queries for Products
	// Creates a new product and returns its full details.
	// Product options should be created separately in a transaction.
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	// Queries for Product Options (Variants)
	// Creates a new option for a specific product.
	CreateProductOption(ctx context.Context, arg CreateProductOptionParams) (ProductOption, error)
	CreateStockHistory(ctx context.Context, arg CreateStockHistoryParams) (StockHistory, error)
	// Deletes a product. Its options will be deleted automatically due to 'ON DELETE CASCADE'.
	DeleteProduct(ctx context.Context, id uuid.UUID) error
	GetDeletedProduct(ctx context.Context, id uuid.UUID) (GetDeletedProductRow, error)
	// Retrieves a product by its ID, including its options.
	GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error)
	// Mengambil satu varian produk berdasarkan ID dan ID produk induknya.
	GetProductOption(ctx context.Context, arg GetProductOptionParams) (ProductOption, error)
	// Retrieves a product option by its ID, including its product details.
	GetProductOptionByID(ctx context.Context, id uuid.UUID) (GetProductOptionByIDRow, error)
	// Retrieves a single product and aggregates its options into a JSON array.
	// This is an efficient way to fetch a product and its variants in one query.
	// Now filters out soft-deleted options.
	GetProductWithOptions(ctx context.Context, id uuid.UUID) (GetProductWithOptionsRow, error)
	GetStockHistoryByProduct(ctx context.Context, productID uuid.UUID) ([]StockHistory, error)
	GetStockHistoryByProductWithPagination(ctx context.Context, arg GetStockHistoryByProductWithPaginationParams) ([]StockHistory, error)
	ListDeletedProducts(ctx context.Context, arg ListDeletedProductsParams) ([]ListDeletedProductsRow, error)
	// Retrieves all options for a single product.
	ListOptionsForProduct(ctx context.Context, productID uuid.UUID) ([]ProductOption, error)
	// Lists products with filtering and pagination.
	// Does not include variants for performance reasons on a list view.
	ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error)
	RestoreProduct(ctx context.Context, id uuid.UUID) error
	RestoreProductsBulk(ctx context.Context, dollar_1 []uuid.UUID) error
	SoftDeleteProduct(ctx context.Context, id uuid.UUID) error
	// Deletes a single product option.
	SoftDeleteProductOption(ctx context.Context, id uuid.UUID) error
	// Updates a product's details. Use COALESCE for optional fields.
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	// Updates a specific product option.
	UpdateProductOption(ctx context.Context, arg UpdateProductOptionParams) (ProductOption, error)
}

var _ Querier = (*Queries)(nil)
