// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stock_history.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countStockHistoryByProduct = `-- name: CountStockHistoryByProduct :one
SELECT COUNT(*) FROM stock_history
WHERE product_id = $1
`

func (q *Queries) CountStockHistoryByProduct(ctx context.Context, productID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countStockHistoryByProduct, productID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStockHistory = `-- name: CreateStockHistory :one
INSERT INTO stock_history (
    product_id,
    change_amount,
    previous_stock,
    current_stock,
    change_type,
    reference_id,
    note,
    created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, product_id, change_amount, previous_stock, current_stock, change_type, reference_id, note, created_by, created_at
`

type CreateStockHistoryParams struct {
	ProductID     uuid.UUID       `json:"product_id"`
	ChangeAmount  int32           `json:"change_amount"`
	PreviousStock int32           `json:"previous_stock"`
	CurrentStock  int32           `json:"current_stock"`
	ChangeType    StockChangeType `json:"change_type"`
	ReferenceID   pgtype.UUID     `json:"reference_id"`
	Note          *string         `json:"note"`
	CreatedBy     pgtype.UUID     `json:"created_by"`
}

func (q *Queries) CreateStockHistory(ctx context.Context, arg CreateStockHistoryParams) (StockHistory, error) {
	row := q.db.QueryRow(ctx, createStockHistory,
		arg.ProductID,
		arg.ChangeAmount,
		arg.PreviousStock,
		arg.CurrentStock,
		arg.ChangeType,
		arg.ReferenceID,
		arg.Note,
		arg.CreatedBy,
	)
	var i StockHistory
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ChangeAmount,
		&i.PreviousStock,
		&i.CurrentStock,
		&i.ChangeType,
		&i.ReferenceID,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getStockHistoryByProduct = `-- name: GetStockHistoryByProduct :many
SELECT id, product_id, change_amount, previous_stock, current_stock, change_type, reference_id, note, created_by, created_at FROM stock_history
WHERE product_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetStockHistoryByProduct(ctx context.Context, productID uuid.UUID) ([]StockHistory, error) {
	rows, err := q.db.Query(ctx, getStockHistoryByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StockHistory{}
	for rows.Next() {
		var i StockHistory
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ChangeAmount,
			&i.PreviousStock,
			&i.CurrentStock,
			&i.ChangeType,
			&i.ReferenceID,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStockHistoryByProductWithPagination = `-- name: GetStockHistoryByProductWithPagination :many
SELECT id, product_id, change_amount, previous_stock, current_stock, change_type, reference_id, note, created_by, created_at FROM stock_history
WHERE product_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetStockHistoryByProductWithPaginationParams struct {
	ProductID uuid.UUID `json:"product_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) GetStockHistoryByProductWithPagination(ctx context.Context, arg GetStockHistoryByProductWithPaginationParams) ([]StockHistory, error) {
	rows, err := q.db.Query(ctx, getStockHistoryByProductWithPagination, arg.ProductID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StockHistory{}
	for rows.Next() {
		var i StockHistory
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ChangeAmount,
			&i.PreviousStock,
			&i.CurrentStock,
			&i.ChangeType,
			&i.ReferenceID,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
