// This file is auto-generated by scripts/gen-rbac.ts
// Do not edit manually.

export const RBAC_RULES: Record<string, string[]> = {
    "GET /activity-logs": [
        "admin"
    ],
    "POST /categories": [
        "admin",
        "manager"
    ],
    "GET /categories/{id}": [
        "admin",
        "manager"
    ],
    "PUT /categories/{id}": [
        "admin",
        "manager"
    ],
    "DELETE /categories/{id}": [
        "admin",
        "manager"
    ],
    "GET /orders": [
        "admin",
        "manager",
        "cashier"
    ],
    "POST /orders": [
        "admin",
        "manager",
        "cashier"
    ],
    "GET /orders/{id}": [
        "admin",
        "manager",
        "cashier"
    ],
    "POST /orders/{id}/apply-promotion": [
        "admin",
        "manager",
        "cashier"
    ],
    "POST /orders/{id}/cancel": [
        "admin",
        "manager",
        "cashier"
    ],
    "PUT /orders/{id}/items": [
        "admin",
        "manager",
        "cashier"
    ],
    "POST /orders/{id}/pay/manual": [
        "admin",
        "manager",
        "cashier"
    ],
    "POST /orders/{id}/pay/midtrans": [
        "admin",
        "manager",
        "cashier"
    ],
    "POST /orders/{id}/print": [
        "admin",
        "manager",
        "cashier"
    ],
    "POST /orders/{id}/update-status": [
        "admin",
        "manager",
        "cashier"
    ],
    "POST /products": [
        "admin",
        "manager"
    ],
    "GET /products/trash": [
        "admin"
    ],
    "POST /products/trash/restore-bulk": [
        "admin"
    ],
    "GET /products/trash/{id}": [
        "admin"
    ],
    "POST /products/trash/{id}/restore": [
        "admin"
    ],
    "GET /products/{id}": [
        "admin",
        "manager",
        "cashier"
    ],
    "DELETE /products/{id}": [
        "admin"
    ],
    "PATCH /products/{id}": [
        "admin",
        "manager"
    ],
    "POST /products/{id}/image": [
        "admin",
        "manager"
    ],
    "GET /products/{id}/stock-history": [
        "admin",
        "manager",
        "cashier"
    ],
    "POST /products/{product_id}/options": [
        "admin",
        "manager"
    ],
    "PATCH /products/{product_id}/options/{option_id}": [
        "admin",
        "manager"
    ],
    "POST /products/{product_id}/options/{option_id}/image": [
        "admin",
        "manager"
    ],
    "GET /promotions": [
        "cashier",
        "admin",
        "manager"
    ],
    "POST /promotions": [
        "admin",
        "manager"
    ],
    "GET /promotions/{id}": [
        "cashier",
        "admin",
        "manager"
    ],
    "PUT /promotions/{id}": [
        "admin",
        "manager"
    ],
    "DELETE /promotions/{id}": [
        "admin",
        "manager"
    ],
    "POST /promotions/{id}/restore": [
        "admin",
        "manager"
    ],
    "PUT /settings/branding": [
        "admin"
    ],
    "POST /settings/branding/logo": [
        "admin"
    ],
    "PUT /settings/printer": [
        "admin"
    ],
    "POST /settings/printer/test": [
        "admin"
    ],
    "POST /users": [
        "admin"
    ],
    "GET /users/{id}": [
        "admin",
        "manager"
    ],
    "PUT /users/{id}": [
        "admin"
    ],
    "DELETE /users/{id}": [
        "admin"
    ],
    "POST /users/{id}/toggle-status": [
        "admin"
    ]
};
