// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
)

type Querier interface {
	// Membuat metode pembayaran baru.
	CreatePaymentMethod(ctx context.Context, name string) (PaymentMethod, error)
	// Mengambil satu metode pembayaran berdasarkan nama untuk pengecekan duplikat.
	GetPaymentMethodByName(ctx context.Context, name string) (PaymentMethod, error)
	// Mengambil daftar semua metode pembayaran yang aktif.
	ListPaymentMethods(ctx context.Context) ([]PaymentMethod, error)
}

var _ Querier = (*Queries)(nil)
