ALTER TYPE log_action_type ADD VALUE 'REGISTER';
ALTER TYPE log_action_type ADD VALUE 'UPDATE_PASSWORD';
ALTER TYPE log_action_type ADD VALUE 'UPDATE_AVATAR';
ALTER TYPE log_action_type ADD VALUE 'LOGIN_SUCCESS';
ALTER TYPE log_action_type ADD VALUE 'LOGIN_FAILED';
